zenoss/ZenPacks.zenoss.Microsoft.Windows

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
when formatting 'failure' it prints out the entire traceback.  leads to confusion so we'll just print out e which will only show the error.
> Fixes ZEN-15793

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
Fix replacement of newline/carriage return +newlines.  Add tabs to be replaced.  There are other escape characters in powershell, but do not see any of the others being used.  Things like alert bell, backspace, vertical tab wouldn't be used in an event message.
https://jira.zenoss.com/browse/ZEN-15911
> Fixes ZEN-15911

- ZenPacks/zenoss/Microsoft/Windows/browser/resources/js/global.js
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
When entering powershell script, variables are denoted using a single '$'.  We'll log error message and send event that script may be malformed.  Also, when creating the pscommand, we were formatting the string twice, resulting in a KeyError if there was an assignment operator('=') in the script.  Fixed the event message to make more sense.
> Fixes ZEN-16834

- ZenPacks/zenoss/Microsoft/Windows/browser/resources/js/global.js
- ZenPacks/zenoss/Microsoft/Windows/datasources/PortCheckDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
Added default graphs for DFS replication counters
Added dcdiag tests for FSMOCheck and VerifyEnterpriseReferences.  Also enabled a way for user to apply extra parameters to a dcdiag test.  Changed severity to errors.
Increased default interval time for port check to 30 minutes.  Also get the scanner logger in scanner subclass instead of windows logger
> Updates for ZEN-16967

- ZenPacks/zenoss/Microsoft/Windows/Device.py
Do not need to update zDeviceTemplates as this creates a local template.  There is some confusion around getRRDTemplates and the bind templates dialog.
> Update for ZEN-17059

- ZenPacks/zenoss/Microsoft/Windows/info.py
should be calling WinService.monitored() instead of getMonitor()
> Fixes ZEN-17308

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
When editing a local copy of service template, there is no deviceclass.
also update the readme
> Fixes ZEN-17318

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
Allow individual zDBInstances to work, but they are no longer required.  Also, build valuemap correctly so we return the correct values for specific databases in a specific instance
> Fixes ZEN-17535

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
when using the default MSSQLSERVER instance we need only supply the server name.  also, stdout will never be empty so we need always check stderr
> Fixes ZEN-18811

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
instances.stdout should contain something like this:
{ instances: 'SQL1', hostname: 'server.name.loc' }
if sql server is not installed, we'll see:
{ instances: , hostname: 'server.name.loc' }
need to skip instances so that we can log no sql server installed and return without further processing.
> Fixes ZEN-18533

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
check for empty events array before building json.  Also add quotes around logname in case of two or more word log names, such as "DNS Server"
> Fixes ZEN-18757

- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
for better performance, we should only run this query once to get all service statuses then parse for monitored services in onSuccess.
> Fixes ZEN-18947

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Software.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testSoftware.py
Fixes https://jira.zenoss.com/browse/ZEN-19637
Make manufacturer ID "Unknown" if Vendor value would not be valid Zope ID.
> ZEN-19637: Missing Software Information for some Windows Devices

- .gitignore
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/WinRMPlugin.py
send ping status for connection refused error in perfmon data source.  this will indicate if a device is down and change the device status on the gui.  we should also be sending /status/ping for the modeler plugins.
> Fixes ZEN-19813

- ZenPacks/zenoss/Microsoft/Windows/basereportable.py
because our device had it's own reportable factory we were not writing out software.  software is not found by ICatalogTool
> Fixes ZEN-19366

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
Graceful handling of empty "SELECT * FROM Win32_OperatingSystem" output,
Fixes https://jira.zenoss.com/browse/ZEN-20015.
> ZEN-20015: WinRM Trace needs improvement

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
shortened the event script to allow for as large an xml query as we can.  this should allow for approximately 4400 characters due to windows shell limit of 8192.  2003 uses a different query than 2008 and up.  We will leave 2003 script in for existing users, but will not be updating it.
Also readme updates
> Fixes ZEN-20185

- ZenPacks/zenoss/Microsoft/Windows/patches/platform.py
Fixes the following error on Zenoss 4:
AttributeError: 'module' object has no attribute '_AgentBase'
Fixes ZEN-20474.
> Only monkeypatch IPv6 support when possible.

- ZenPacks/zenoss/Microsoft/Windows/ClusterDevice.py
Fixes https://jira.zenoss.com/browse/ZEN-19993
If you have already added cluster node by FQDN and this FQDN resolves in IP different from known and reported by cluster, then possible no devices would be found by 'clusterhostip', so the second one check might handle this case.
> ZEN-19993: Microsoft windows cluster failing to model

- ZenPacks/zenoss/Microsoft/Windows/browser/resources/js/device.js
must have been oversight.  apppool data was there, but no column added.
> add application pool column.

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
Fixes https://jira.zenoss.com/browse/ZEN-20149
> ZEN-20149: Friendly message if EventLog datasource is not valid.

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/IISSiteDataSource.py
https://jira.zenoss.com/browse/ZEN-21029
Version 7 and up of IIS uses same namespace and wmi class.  Better to check the version in the ZenPack.  This also helps with debugging
> Fixes ZEN-21029

- ZenPacks/zenoss/Microsoft/Windows/tests/testWinCluster.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
Traceback occurs when we pass in empty string to sizeof_fmt.  int('') returns ValueError.  If the data is empty, we should show 'N/A' since it's not available.  This func is called in WinCluster modeler plugin and ShellDataSource
> Fixes ZEN-21242

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/Device.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/WinRMPingDataSource.py
put winrm ping status in /Status/WinRM then use that for device status.  this way it will still collect on zenpython and not go into pause status
> Fixes ZEN-21270

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
Similar fix as in https://jira.zenoss.com/browse/ZEN-21242.  Problem is that not all cluster disks are local to the node and some information may not be found when looping through results of call to get-clusterresource.  Also moved $diskinfo outside of the loop as this only needs to be done once.
> Fixes ZEN-21325

- ZenPacks/zenoss/Microsoft/Windows/browser/resources/js/global.js
Added Ext.onReady() around logic.  Creating the dialog broke the page during loading.  So, now we will wait until the page is done loading before showing message
> Fixes ZEN-21355

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
This commit was not picked up during the release of 2.5.0.  Adding it in now.  Cherry-picking 90ca4b4d59418ea064669e1e33162d45d6861256 into hotfix.
> Revert previous changes to this branch

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/tests/testFileSystems.py
- ZenPacks/zenoss/Microsoft/Windows/tests/utils.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
Fixes https://jira.zenoss.com/browse/ZEN-21351.  If the size and/or freespace is missing, then we should return True to stay in line with the change implemented in https://jira.zenoss.com/browse/ZEN-19213.  Updated unit test to check for this as well.
> Fixes ZEN-21351

- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
setters are only called when something changes anyway.  we need to reindex whenever alertifnot, startmode, or in_exlcusions changes.
> fixes ZEN-21603

- ZenPacks/zenoss/Microsoft/Windows/WinService.py
We need to check to make sure that someone hasn't added a non-ServiceDataSource to a Windows service monitoring template
> Fixes ZEN-21899

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
Send severity to cmd parser so that it can use datasource severity
Tested by creating custom parser and setting severity to something other than 3(Warning)
https://jira.zenoss.com/browse/ZEN-21928
> fixes ZEN-21928

- ZenPacks/zenoss/Microsoft/Windows/ClusterDisk.py
- ZenPacks/zenoss/Microsoft/Windows/ClusterInterface.py
- ZenPacks/zenoss/Microsoft/Windows/ClusterNetwork.py
- ZenPacks/zenoss/Microsoft/Windows/ClusterNode.py
- ZenPacks/zenoss/Microsoft/Windows/ClusterResource.py
- ZenPacks/zenoss/Microsoft/Windows/ClusterService.py
- ZenPacks/zenoss/Microsoft/Windows/browser/resources/js/device.js
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/info.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
Fixes https://jira.zenoss.com/browse/ZEN-22345 for zendesk ticket https://zenoss.zendesk.com/agent/tickets/111650.  We should not be applying datamaps to possibly thousands of components every 5 minutes.  The datapoint was already defined for state, so let's tie into it.  Use pingStatus for 'Up' renderers also.
Also, some PEP8 stuff
> Fixes ZEN-22345

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
Fixes https://jira.zenoss.com/browse/ZEN-22369
Non empty tuple converted to boolean in true, so modeler marks host as DC
> ZEN-22369: Improperly setting the Active Directory Template

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
Fixes ZEN-20232
This adds a check for .NET 3.5 installed.  Required for using
Get-WinEvent cmdlet.  Also, we should not be writing to HKLM.
Write to HKCU instead, no special permissions required.
> Add check for .NET 3.5.

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
Fixes ZEN-20232
result is not iterable.  we should look at the actual message
we probably won't see this message anymore, but just in case
it slips by we'll keep it.
> Look for string in message, not result instance

- README.mediawiki
Fixes ZEN-22904
because LogAlways is 0 using a less than or equal to Warning query
will return these mainly informational events.
> Document LogAlways event level

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/modeler/WinRMPlugin.py
Fixes ZEN-23010
Need to send a clear event for successful shell/powershell commands.
Tested by sending a critical event, then remodeling
> Send clear event on successful model for powershell commands

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/WinService.py
Fixes ZEN-23063
Check for attribute.  it could be missing due to the wrong datasource
inside of a service template.  or an old datasource that has not been updated
> Check for 'in_exlusions' attribute on datasource

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- ensure that double-quote-delimited attribute/value pairs remain that
way
- ensure that IOStream file object is closed properly
> Fixes EventLogDataSource XML formatting issues

- ZenPacks/zenoss/Microsoft/Windows/utils.py
Fixes ZEN-23183
For basic auth, a 401 http code is returned.  This could mean
bad username/pass combo or it could mean expired.  We'll send the
event so users know to check their password.
> Add check for basic auth password error

- ZenPacks/zenoss/Microsoft/Windows/Device.py
- Rewrote Device getRRDTemplates method to abstract the various software
detection criteria to their own methods, where they can be fine-tuned
further if needed.
> Fixes ZEN-22640

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/WinRMPingDataSource.py
Fixes ZEN-22166
Updated the readme to explain winrm ping and why it's better than a
simple ping.  Also, we'll add any error message to the device down summary
so users will know why it's down.
> Make winrm ping more understandable

- ZenPacks/zenoss/Microsoft/Windows/tests/testIISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testProcessDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testWinCluster.py
- Python twisted Failure object is different in 5.x, so rewrote to
account for differences.
> Fixes ZEN-23326

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/info.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Services.py
- ZenPacks/zenoss/Microsoft/Windows/resources/js/global.js
Fixes ZEN-20148
Subclass platform WinService so services will be shown on services
page.  Existing winrmservices will be removed on a remodel.  Users
can enable monitoring on services page now.  Remove deprecated
message when navigating to windows services page
> Enable the windows services page

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- reducing the maintencance interval to 300 for perfmondatasource
- suspect that the 600s interval is behind the additional polling for invalid, removed file systems, but don't have ability to confirm.
> Fixes 22240

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
- remove ClusterService components from modeler output if they have no
associated ClusterResources
> Fixes ZEN-23412

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
Fixes ZEN-19615
Subclass interface and info off of base and add in only what we need
Change event class to /Status/WinService
We should not allow users to select an event class for service monitoring.
We need to see status by looking in /Status/WinService.
> change subclass for service datasource info

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Interfaces.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testInterfaces.py
Fixes ZEN-23379
Fix unit test to account for Interfaces modeler change
> We only need to set the perfmon counter on physical adapters

- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/info.py
- ZenPacks/zenoss/Microsoft/Windows/interfaces.py
- ZenPacks/zenoss/Microsoft/Windows/resources/js/global.js
- override WinService's getFailSeverity method to take into account
template-based  as well as service class severities
- revise ServiceDataSource to use WinService's getFailSeverity
- revise info.py and interface.py to include Fail Severity drop-down
(subclass WinServiceInfo/IWinServiceInfo)
- preserve info.py/interface.py overrides for usermonitor property
- revise javascript to better align with legacy while providing
formatting enhancements (column width)
- Revised template datasource identification method
> Fixes ZEN-23713

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/interfaces.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Services.py
Fixes ZEN-23761
Added option to reset manually set monitoring for a service.
Fixed missing Details info, added Description to the modeler plugin
> Index services when datasource has been enabled/disabled

- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
Also, when serviceClass is not an attribute this can cause a 'configuration not found' error running zenpython
> Fixes manual monitoring

- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
- disable WinRMPing datasource by default
> Fixes ZEN-23517

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/WinRMPingDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
Fixes ZEN-23517
Many customer/support complaints that this should not be enabled
by default.
> disable datasource by default

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/FileSystems.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testFileSystems.py
Fixes ZEN-23800
If a disk has no size we wouldn't be able to correctly monitor it.
> Do not model disks with no capacity/size

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Interfaces.py
Fixes ZEN-23834
We don't support 2003, but we shouldn't traceback on it either
> account for 2003 lack of PhysicalAdapter property

- ZenPacks/zenoss/Microsoft/Windows/zope_utils.py
Fixes ZEN-23967
Other zenpacks rely on the Windows zp.  Added this back in for
compatibility
> Need to keep this file for backwards compatibility

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/OSProcess.py
Fixes ZEN-24010
> 2016-07-12 17:18:20,624 ERROR zen.hub: Unhandled exception in zenhub service ZenPacks.zenoss.PythonCollector.services.PythonConfig.PythonConfig: zAlertOnRestart 
Traceback (most recent call last): 
> File "/opt/zenoss/Products/ZenCollector/services/config.py", line 117, in _wrapFunction 
return functor(*args, **kwargs) 
> File "/opt/zenoss/Products/ZenCollector/services/config.py", line 261, in _createDeviceProxies 
proxy = self._createDeviceProxy(device) 
> File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.PythonCollector-1.7.4.egg/ZenPacks/zenoss/PythonCollector/services/PythonConfig.py", line 73, in _createDeviceProxy 
self.component_datasources(component, collector)) 
> File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.PythonCollector-1.7.4.egg/ZenPacks/zenoss/PythonCollector/servi …
> Device was being returned for the class object. should be OSProcess

- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/jobs.py
- ZenPacks/zenoss/Microsoft/Windows/patches/platform.py
https://jira.zenoss.com/browse/ZEN-23827
As re-indexing of all affected WinServices takes to much time, moved this operation to zenjobs to don't block UI.
> ZEN-23827: Editing a Windows Service (WinService) Locks Up Zope and Times Out

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ZenPacks/zenoss/Microsoft/Windows/configure.zcml
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/handlers.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testServiceDataSource.py
Fixes ZEN-24165
Enabling/disabling monitoring for a service should obey the 4 laws
Simplified the monitored() method.  We can get all the
information we need from the context when a datasource is created.
We know which services are monitored because there are datasources
for the ones that are being monitored.  We should also reindex
services if a datasource is removed.
update readme
fix version #
> Service monitoring should follow the order of precedence

- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
Fixes ZEN-24165
We need to look through all other datasources to see if a service
needs to be excluded from monitoring.  Also, no need to split up
configs by datasource id.  This can causes multiple queries for the
same service, which floods the system with unnecessary events.
> Make sure a service is not excluded

- ZenPacks/zenoss/Microsoft/Windows/WinService.py
Fixes ZEN-24165
re.IGNORECASE does not match within the compiled regex in the match() method.
Move it to re.compile() and it does work
> Fix regex not matching

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/migrate/AddOSRelations.py
- ZenPacks/zenoss/Microsoft/Windows/progresslog.py
- ZenPacks/zenoss/Microsoft/Windows/tests/test_AddOSRelations.py
- ZenPacks/zenoss/Microsoft/Windows/tests/utils.py
7a2024c added clusternetworks and clusternodes relationships to the
OperatingSystem class, but it didn't include a migration script to get
those relationships added to existing devices. This can result in errors
such as the following in UI flares, and perhaps elsewhere.
AttributeError: clusternetworks
Partially fixes ZEN-24401.
> Migrate for OS relations added in 2.5.0

- ZenPacks/zenoss/Microsoft/Windows/migrate/ResetClassTypes.py
The RemoveWinRMServices migration script that's also targeted at 2.6.3
removes all WinRMSerice instances that this migration script was
reindexing. Due to ZenPackCmd performing all migrations within the same
paused(onIndexingEvent) context manager this lead to a situation where
the deferred indexing if WinRMService instances would fail with the
following traceback.
...
File "/opt/zenoss/Products/Zuul/catalog/global_catalog.py", line 287, in searchExcerpt
o.name(), o.device().titleOrId())
AttributeError: 'NoneType' object has no attribute 'titleOrId'
This bug was introduced in 68a2b76. I thought the omision of WinService
indexing was accidental, so I added it. In retrospect the omission was
necessary.
The simple solution is to stop reindexing WinRMService instances that
are going to be …
> Omit WinService from ResetClassTypes migration

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/WinService.py
Fixes ZEN-24528
If a user has copied the default template in order to disable monitoring
we should honor that before any other datasources in the default template
> Respect Component WinService template over all others

- ZenPacks/zenoss/Microsoft/Windows/Device.py
Fixes ZEN-24556
First check if there is a winrmping down event.  if there are none
then check the ping status.
> Check ping status if there are no winrm ping status problems

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/actions.py
- ZenPacks/zenoss/Microsoft/Windows/txwinrm_utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZEN-24583
We will now allow for the WSMAN spn to be used when HTTP/HTTPS cannot.
> Add the ability to use WSMAN spn

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Processes.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testProcesses.py
Fixes ZEN-25311
We need to populate object title with object displayName.
Otherwise object id will be used as title, and we don't want that.
Update unit test as well.
> Assign object displayName to object title

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- ZenPacks/zenoss/Microsoft/Windows/zenpacklib.py
When zenpacklib is used with both zenpacklib.Component and a platform
component model classes such as IpInterface as base classes, some of the
platform model class' functionality is list. Specifically in this case
the IpInterface.index_object() method was never being called when
Windows Interface.index_object() was called. There's important
functionality in IpInterface.index_object() that must be used.
This fix enhances zenpacklib to provide a proxy base type for all
platform component model classes. This allows single-inheritence to be
used in zenpack.yaml, which greatly simplifies the ZenPack's job because
zenpacklib can take on the responsibility of making sure base class
functionality is used when appropriate.
Fixes ZEN-25559.
> Fix partial subclassing of platform model classes

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
Fixes ZEN-24633
Windows may not have v3.5 installed but does have v4+. Improved test
using regex to look for 3.5, 4, or 5 in the future
> Fix test for .net 3.5+

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/MigrateSQLInstances.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZEN-25851
Multiple versions of sql server can co-exist.  we should only load
the assembly for the version of the instance we're modeling/monitoring.
This will also display the current version
> Only load the assembly version needed for the instance

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Processes.py
Fixes ZEN-25311
Changes in 2.6.6 correctly subclassed OSProcess so setting 'title'
became unnecessary, and as it turns out, destructive.  Zendesk ticket
> Revert change from ZEN-25311

- ZenPacks/zenoss/Microsoft/Windows/tests/testProcesses.py
plugin.process() no longer sets title on an ObjectMap instance. The change to the test should've been reverted along with the reversion in commit b10e4a1fe9e6baef981ffec42272691d92a3edce
> FIX ZEN-26086, Unit Test Failure, Remove assertEquals(ObjectMap.title, ObjectMap.displayname)

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/WinSQLDatabase.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZEN-26226
We shouldn't be applying objectmaps during monitoring.  this bogs down
zenhub.  set a simple status value that we can query.
> Don't send objectmaps to bog down zenhub

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/WinSQLDatabase.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- ZenPacks/zenoss/Microsoft/Windows/zenpacklib.py
Fixes ZPS-453
OSComponents should also use the same info/interface classes as a Component
Also, getStatus is a reserved name, changed to getState
> Fix AttributeError, missing 'uuid' in zope

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/FileSystem.py
- ZenPacks/zenoss/Microsoft/Windows/HardDisk.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/WinRMPlugin.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/HardDisks.py
- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- ZenPacks/zenoss/Microsoft/Windows/zenpacklib.py
Fixes ZPS-479
This adds the Hard Disk component and modeler plugin to the ZenPack.
Models Hard Disk and finds associated file systems.  Links to File
System and provides a reverse link back to the Hard Disk.
TODO: Add Monitoring template
> Add support for Hard Disks in Windows

- ZenPacks/zenoss/Microsoft/Windows/datasources/ProcessDataSource.py
- Fixes ZPS-316
- Corrected invalid "...Persec" entries in valid datapoint list
- Changed "remove" method call (which operates on single element of set)
to "difference_update", which has the desired effect.
> Ensure valid ProcessDataSource datapoint names (ZPS-316)

- ZenPacks/zenoss/Microsoft/Windows/OSProcess.py
- ZenPacks/zenoss/Microsoft/Windows/configure.zcml
- ZenPacks/zenoss/Microsoft/Windows/info.py
- ZenPacks/zenoss/Microsoft/Windows/interfaces.py
- ZenPacks/zenoss/Microsoft/Windows/patches/platform.py
- Fixes ZPS-572
- override _instanceClass attribute in ProcessFacade so that OSProcess
subclass is included
- Also removed unneeded info/interfaces/override code for OSProcess
class
> Ensure Windows Process display in Processes UI (ZPS-572)

- ZenPacks/zenoss/Microsoft/Windows/FileSystem.py
- ZenPacks/zenoss/Microsoft/Windows/HardDisk.py
- ZenPacks/zenoss/Microsoft/Windows/Interface.py
- ZenPacks/zenoss/Microsoft/Windows/TeamInterface.py
- ZenPacks/zenoss/Microsoft/Windows/configure.zcml
- ZenPacks/zenoss/Microsoft/Windows/info.py
- ZenPacks/zenoss/Microsoft/Windows/interfaces.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- With ZPL2.0, some info/interfaces and subclass code is no longer
needed, so removing it
- info/interfaces for Interface, TeamInterface is left in place since
these do not yet inherit properly from platform (ZPS-494)
> Remove unneeded Interfaces/info/subclass code

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- Issue caused by lack of "instancename" attribute on context that is
not WinSQLInstance
- Changed direct reference to instancename to a getattr() instead
> Fix AttributeError for ShellDataSource (ZPS-506)

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
Fixes ZPS-701
* Parameter keyword is ps_script, not ps_command
> use ps_script, not ps_command

- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/handlers.py
Fixes ZPS-570
* Check for -new, -backup, -preupgrade so that we do not start job
> Do not run service indexing job on temporary templates

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- Newer versions of PythonCollector omit datapoints without a valid
config
- added get_dummy_dpconfig to provide a datapoint config for "status"
datapoint returned by PowershellMSSQL strategy
> Fix missing status datapoint for ShellDatasource

- ZenPacks/zenoss/Microsoft/Windows/WinSQLInstance.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- Fixes ZPS-299
- Updated WinSQLInstance getStatus method to return 1 if any events
- Updated WinSQLDatabase "getState" method to first check WinSQLInstance
state
- Updated ShellDataSource to generate events for every affected
component when a query fails
- added built-in "status" datasource to WinDatabase template so that
"cacheRRDValue" will work
> MSSQL Database state should reflect instance status (Fixes ZPS-299)

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Interfaces.py
- Fixes ZPS-726
- Revised handling of "pnpentities" and Win32_PnpEntity data from
modeler results
> Fix tracebacks in Interfaces modeler plugin (ZPS-726)

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
- Fixes ZPS-563
- set default "domain_controller" to False
- perform hasattr/getattr testing on "computerSystem" object for
"DomainRole" attribute
> Fix AttributeError in OperatingSystem modeler plugin (ZPS-563)

- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ZenPacks/zenoss/Microsoft/Windows/interfaces.py
Fixes ZPS-632
* Underlying class depends upon monitoredStartModes being populated.
Populate it with the appropriate start modes depending upon how
service is being monitored
* Also make it clear that the checkbox for usermonitor does not enable/disable monitoring
* Make sure that DefaultService has startmodes attribute
> Ensure that status will display up/down

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/WinService.py
Fixes ZPS-661
* Some templates may end up with a bad datasource that is not a
Windows Service datasource.  Skip them
> Make sure datasource has startmode attribute

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/handlers.py
Fixes ZPS-570
* Only run reindexing job if one is not pending or if it is not a
temporary ZPL template.
> No need to start reindexing job if one is pending

- ZenPacks/zenoss/Microsoft/Windows/OSProcess.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/ResetOSProcesses.py
- ZenPacks/zenoss/Microsoft/Windows/patches/platform.py
- Fixes ZPS-572
- Reverted earlier partial fix (platform patch)
- Updated setup.py dependency to ZenPackLib 2.0.2 (forthcoming), which
contains the actual fix
- added ResetOSProcesses migrate script for existing OSProcess objects
- removed "getClassObject" method from OSProcess override (no longer
needed)
> Fix Processes GUI display (ZPS-572)

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
Fixes ZPS-713
* Remove exception for non-domain user running dcdiag.
* Allow for non-domain user to be sent in on command line
> No need for user to be a domain user to run dcdiag

- ZenPacks/zenoss/Microsoft/Windows/ClusterDevice.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- Fixes ZPS-581
- added zWinRMClusterNodeClass ZProperty
- zWinRMClusterNodeClass specifies the device class path under which
node devices are automatically created by WinCluster modeler plugin
> Specify Device Class for Cluster Nodes (ZPS-581)

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- Fixes ZPS-788
- Change references to "id" to params.get('eventid'), which contains the
datasource id
> Fix EventLogDataSource AttributeError (ZPS-788)

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Fixes ZPS-660
* Cluster does not have sql version info, so go with 0 for now until
we can figure out versioning
> Set sql version to 0 for clusters

- ZenPacks/zenoss/Microsoft/Windows/migrate/AddHardDiskPlugin.py
Fixes ZPS-427
* ZPL 2.0 does not update existing z properties for existing
device classes.  Until that's cleared up, we'll add through
the migration step.
> Add HardDisks plugin through migrate script

- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
Fixes ZPS-811
* In case an event exists for a service that changes from monitored
to unmonitored we'll send a clear event
> Send clear event for unmonitored services

- ZenPacks/zenoss/Microsoft/Windows/migrate/MigrateEventClassSeverity.py
- Fixes ZEN-26632, ZEN-24633
- Issue caused by local setting of "zEventSeverity" on
/Events/Win/evtsys
- Added MigrateEventClassSeverity script to remove local override on
event class
> Preserve Windows Event Log event severity (ZEN-26632)

- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
Fixes ZPS-811
* Makes more sense to let the events hang around and have them manually
removed so that the users know for sure why the events are gone
> Revert previous change

- ZenPacks/zenoss/Microsoft/Windows/__init__.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- ZenPackLib support for zproperty label/description is being pushed
back to 2.1.0, so migrating these YAML attributes to the ZenPack class
override, which will remove ZPL version specificity from this Windows
release.
> Migrate ZProperty Label/Descriptions to ZenPack Class override

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- Fixes ZEN-26853
- Issue reproducable if target eventClass doesn't exist
(/Status/Interface)
- Added YAML event class for /Status/Interface with remove equal to
False
- Did the same for /Status/OSProcess
> Ensure EventClass set for Interface template threshold (ZEN-26853)

- README.mediawiki
* Fixes ZPS-556
"If you see 100% CPU usage on a domain controller and your forest functional level is Windows 2003 or Windows 2008, you could be missing the WinRMRemoteWMIUsers__ security group." needs to stay because they could still have a windows 2003 functional level.  This does not indicate any sort of support for 2003 servers, only AD functional level.
> Remove 2003 references

- ZenPacks/zenoss/Microsoft/Windows/HardDisk.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-939
If the link to the storage disk/lun can be found, add the link
to hard disk details.
> Add link to storage disk/lun for hard disk

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
Fixes ZPS-955
* Decode counters to utf-8 when building counter map
* Decode counter names from output of get-counter command to utf-8
to match with our counter map
> Make sure we're using unicode strings for counters

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/FileSystems.py
Fixes ZPS-956
Issue warning on bad regex in zFileSystemMapIgnoreNames
> Check for bad regex in zFileSystemMapIgnoreNames

- ZenPacks/zenoss/Microsoft/Windows/tests/testEventLogDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testIISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testServiceDataSource.py
Fixes [https://jira.zenoss.com/browse/ZPS-1014](https://jira.zenoss.com/browse/ZPS-1014)
`datasource` attribute of Datasource instance have to be a string.
> ZPS-1014: update ds mocks according to the recent changes

- ZenPacks/zenoss/Microsoft/Windows/FileSystem.py
- ZenPacks/zenoss/Microsoft/Windows/OSProcess.py
- ZenPacks/zenoss/Microsoft/Windows/TeamInterface.py
- ZenPacks/zenoss/Microsoft/Windows/WinIIS.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- Fixes ZPS-292
- changes rrdPath method on some component classes to revert to older
behavior for Zenoss 4.x
- Since issue affects multiple classes besides interface, these were
updated as well
- Although this update does not recover lost data, it will prevent
further loss while eliminating it altogether for direct upgrades from
2.6.2
> Revert to legacy rrdPath (ZPS-292)

- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ZenPacks/zenoss/Microsoft/Windows/info.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Services.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-1005
* Add flag so that we index services on a remodel
* Override monitored property for info so that we can pull the current
indexed values of the service.  Gives visual confirmation that a service
is monitored or not.
* Remove unecessary/invalid class props/zprops from yaml
> Index services on model update no matter

- ZenPacks/zenoss/Microsoft/Windows/migrate/RemoveWinRMServices.py
- Fixes ZPS-984
- These errors occur as a downstream effect of "winrmservices" component
removal via relation deletion during migration.  Since deleting the
relation causes the related components to deleted simultaneously, this
causes a spurious uncatalogObject warning that can be disregarded.  The
"suppress_events" flag has been added, which should prevent these
warnings from being seen by the user.
> Suppress uncatalog errors during upgrade (ZPS-984)

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/IISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/PortCheckDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- Fixes ZPS-573
- Updated log messaging for custom datasources to include the
device/component ids where available.
> Logging should include device and component where relevant (ZPS-573)

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
Fixes ZPS-831
The critical event was being sent to the wrong event class
> Add event to correct event class

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/HardDisks.py
Fixes ZPS-1205
win2003 is not supported, but we should not traceback if modeling one
> Don't blow up even if modeling a non-supported device

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Fixes ZPS-850
Pull out the exception from the event message.
Add questions to message to be sure the server is online,
and the user has the correct permissions and credentials entered correctly
> Sanitize powershell error message

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/__init__.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/MigrateRRDPaths.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Goal is to minimize data loss resulting from zenpacklib conversion
within different upgrade scenarios
- Fixes ZPS-1204
- Adds zWinUseLegacyRRDPath zProperty to control whether old or
new-style (ZPL) rrdPath is used for RRD storage
- Added MigrateRRDPaths migrate script to auto-determine this behavior
- updated rrd_path method to choose conditionally based on
zWinUseLegacyRRDPath
- Updated readme.mediawiki with documentation regarding new zProperty
and the related issues
> RRDPath migration issue should depend on upgrade path (ZPS-1204)

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/WinSQLDatabase.py
- ZenPacks/zenoss/Microsoft/Windows/__init__.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/MigrateRRDPaths.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- Updated fix for ZPS-1204
- Changes previously introduced zProperty into an attribute stored on
dmd, set by install migration script that determines its value.
- Removes user visibility while still preventing the data loss
associated with rrdPath changes from zenpacklib conversion
> Remove user visibility of fix for ZPS-1204

- ZenPacks/zenoss/Microsoft/Windows/migrate/AddHardDiskPlugin.py
- Fixes ZPS-1233
- updated AddHardDiskPlugin migrate script to include sub-device classes
and devices using local zCollectorPlugins override.
> Add HardDisks modeler plugin to overridden objects (ZPS-1233)

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- Fixes ZPS-562
- Issue was caused by use of non-unique eventClassKey across multiple
event classes, so removed the undesired settings.
> Remove duplicate auth failure events (ZPS-562)

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- Fixes ZPS-1231
- Although technically this is not from the EventLogDataSource, this
particular ShellDataSource event was updated to use the first sentence
only for event summary, while keeping the entire output for the message
field.
> Reduce verbosity in event summary field (ZPS-1231)

- ZenPacks/zenoss/Microsoft/Windows/__init__.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testAuthErrEvents.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- Fixes ZPS-562
- Ensure that authentication-related console events are cleared
- Revised structure of event classes and mappings to more simply handle
various use cases
- Prevent and ensure removal of duplicate clear events (which was the
root of the problem)
- Updated testAuthErrEvents unit test
> Revise and simplify auth-related event handling (ZPS-562)

- ZenPacks/zenoss/Microsoft/Windows/utils.py
- Fixes ZPS-1293
- Remove 'datasources' field from generic events, since it occupies too
much screen real estate in the event details GUI
> Remove 'datasources' field from event details (ZPS-1293)

- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- WinService should attempt to set failSeverity by acquisition first
before using the default.
> Inherit WinService severity from ServiceClass by default

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- docs/body.md
Update ShellDataSource WinSQL Instance to reflect template severity
choice instead of hard-coded value
> WinSQLInstance events should honor template severity (ZPS-1323)

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- docs/body.md
- Fixes ZPS-1341
- Update ServiceDataSource to provide timestamp along with status
datapoint.
> Explicit timestamp for WinService state datapoint (ZPS-1341)

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/jobs.py
- docs/body.md
Fixes ZPS-1342
This should reduce the overall number of services that need to be
reindexed.  We'll look at the template id to see if it is an actual
Service Name.  Next we'll make a query out of the in_exclusions regex
to send into ICatalogTool.  There's no need to index services that
would not be affected.
> Make getAffectedServices smarter

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- docs/body.md
Fixes ZPS-1404
we surround a counter with double quotes.  powershell attempts to
evaluate the $ in some counters the same as bash.  use the powershell
escape char (`) so that we can poll these counters
> Make sure that $s use the powershell escape(`) if in double quotes

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/OperatingSystem.py
- ZenPacks/zenoss/Microsoft/Windows/jobs.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/RemoveWinRMServices.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/ResetClassTypes.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- docs/body.md
fixes ZPS-1442
* winrmservices should no longer be a relationship on a windows device
* remove it from the os and from the modeler plugin.
* also no need to try and remove in migrate script
> remove winrmservices relation from OperatingSystem

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/migrate/AddStateToWinService.py
- docs/body.md
Fixes ZPS-1473
Using catalog to find templates and only look at those with a targetPythonClass
of ZenPacks.zenoss.Microsoft.Windows.WinService.  Much faster than looking at
individual services
> Improve speed of migrate script

- ZenPacks/zenoss/Microsoft/Windows/tests/testPerfmonDataSource.py
Fixes ZPS-1493
removed the function as it is no longer necessary
> remove test for unused convert_to_ps_counter function

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/Device.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/IIS.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- docs/body.md
Fixes ZPS-1576
move is_iis to a boolean device property.  set this when IIS
modeler plugin is used
> Change is_iis to a boolean, apply during modeling iis components

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- docs/body.md
Add the state datapoint in the plugin's constructor when the task is
built instead of on each collection cycle.
Fixes ZPS-1604.
> Fix redundant service state metric publishing

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/modeler/WinRMPlugin.py
- docs/body.md
Fixes ZPS-1608
Really draw attention to the fact that a device can't be modeled
> Make sure event gets posted so user knows device can't be reached

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- docs/body.md
Fixes ZPS-1693
If we know the failures are expected, there's no need for a warning
> Make expected receive failure logs debug instead of warning

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/migrate/RenameClusterDatasource.py
- docs/body.md
Fixes ZPS-1697
Replace any subclassed "powershell Cluster" datasources with the new
ClusterDataSource.  Also remove errant Cluster template that was
introduced in 2.7.0.
> Add migrate script for cluster datasource

- .gitignore
- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/__init__.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/IISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/RemoveEventInst.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testAuthErrEvents.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testEventLogDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testIISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testPerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testProcessDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-1752
Consolidate kerberos errors into one event.
Add Clear severity to clear events so event server does not need to process them
Update unit tests
IISSiteDataSource should send a clear for sitecheck Running and use the ds severity for not running or unknown
Remove superfluous KerberosAuthenticaion event instances
> Reduce load on event server

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/IISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ProcessDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/WinRMPingDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/__init__.py
- docs/body.md
Fixes ZPS-1692, ZPS-1693
twisted 11 doesn't have ResponseNeverReceived error.  check for both
ResponseNeverReceived and ConnectionLost so that we don't log unnecessarily.
> write ConnectionLost errors to debug

- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
Event Class now displayed in data source template config and events default to /Status.
Fixes ZPS-1810
the eventclass object was set to '/Status' in ClusterDataSource and PerfmonDataSource classes.
> Fixes ZPS-1810

- README.mediawiki
- docs/body.md
Fixes ZPS-1853
Because the other modeler plugins are not run, we can't send in empty ObjectMaps to remove components.
> Advise users to remove non-cluster components from Cluster device

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/WinSQLDatabase.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/AddDPToIISDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/AddDPToWinDatabaseTemplate.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- docs/body.md
Fixes ZPS-1154
Change how we are saving and displaying status for a sql database.
Connecting to zep and searching was taking too much time. Now we'll
use a bitmask to find and display the statuses from a datapoint.
> Speed up loading of database components in 5.2.x+ grid

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
Fixes [ZPS-1860](https://jira.zenoss.com/browse/ZPS-1860).
> Escape double quotes in selector for EventLog datasource.

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- docs/body.md
Fixes ZPS-2031
Show MSSQLSERVER as the instance name.  Add new perfmon_instance
attribute to hold the perf counter instance name.  \SQLServer for
default MSSQLSERVER, \MSSQL${instance_name} for a named instance.
Also added in some default instance counters out of the box.
> Make sure we show default sql server instance

- README.mediawiki
- docs/body.md
Fixes https://jira.zenoss.com/browse/ZPS-1286.
Pipe symbol in strings (required for Nagios-style reporting) was
interpreted by PowerShell.
> ZPS-1286: Document limitations of double quotes in Write-Host commands

- README.mediawiki
- docs/body.md
Fixes ZPS-2108
ZPL 2.0 will not overwrite zprops in existing device classes.  Add
comment noting how to disable snmp monitoring for microsoft device class.
> Add note to readme to disable snmp monitoring

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- docs/body.md
Possibly Fixes ZPS-2075
Revert perfmondatasource run time for get-counter to 10 minutes.
This could make a difference so that we restart the command sooner.
> Possible fix for data gaps

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
Fixes ZPS-2055
contextcompname is only used for sql instances.  we should have been
using dsconf.component
> use component name, not contextcompname for component

- ZenPacks/zenoss/Microsoft/Windows/migrate/RemoveEventInst.py
Fixes ZPS-2103
Change the order of removal in the migrate script.  Trying to remove
a mapping instance after the event class is removed will not work
> Change order of ops in migrate script

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testWinMSSQL.py
- docs/body.md
Fixes ZPS-2143
Not all of the tabs were being printed from the powershell script.
Changed formatting to use 'job_<property>' so that we're not dependent
on some sort of specific characters which may or may not print.
This only seems to affect jobs.  databases and backups not affected.
> Reformat job results in powershell

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- docs/body.md
Fixes ZPS-2142
This will allow users to specify ${here/id} tales expression for a component
datasource.
> use component for component datasources, contextcompname for device

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/IISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/PortCheckDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ProcessDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/WinRMPingDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/txcoroutine.py
- docs/body.md
Fixes ZPS-1765
This will add in a replacement for defer.inlineCallbacks so that
deferreds that need to be cancelled will be cancelled in the callback
tree.  code is BSD from https://github.com/eallik/txcoroutine
Found in twisted bug conversation https://twistedmatrix.com/trac/ticket/4632
Also, add the decorators to EventLogDataSource, PortCheckDataSource, ProcessDataSource,
which were not using inlineCallback.
update txcoroutine pieces in GNUmakefile
update readme
> Add in txcoroutine as replacement for inlineCallbacks

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testAuthErrEvents.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- docs/body.md
Fixes ZPS-2242
Certain twisted errors return a list of exceptions in a list as the message.
This will stringify them so we can check for kerberos or other specific errors.
Also added comment to OperationTimeout debug message to show that it's expected.
> make sure error is string, not list

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-2193
domain_controller doesn't need a label. probably from zpl conversion
> remove duplicate label

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- docs/body.md
Fixes ZPS-2252
There's no need for the no output message.  Any issues with a custom
datasource will be reported anyway.  Some custom commands may not return
datapoints and are working as expected.
> Remove unnecessary event/log message

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/__init__.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/IISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ProcessDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/WinRMPingDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testAuthErrEvents.py
- ZenPacks/zenoss/Microsoft/Windows/txwinrm_utils.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- docs/body.md
Fixes ZPS-2068
since kerberos events are reported from a central location in utils.py,
we can keep track of how many times a false event is going to be sent.
if the number of events exceeds this threshold, we'll send an event.
if a connection succeeds while checking the count, then we can reset
the counter.
> Add kerberos error event threshold for false negative events

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testPerfmonDataSource.py
- docs/body.md
Fixes ZPS-2298
Powershell expands text inside of double quotes, so for some Exchange Server
counters, '==>' was being evaluated as an expression which threw a strange error
stating a file was in use by another process.  Changing to use single quotes
so literal strings can be passed.  this could cause issue with some foreign
language counters because they may contain the unicode apostrophe u'\u2019' which
would act as a closing single quote, so we will surround them with double quotes.
update unit test for perfmon
> surround counters with single quotes so they do not expand

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testPerfmonDataSource.py
Fixes ZPS-2298
This will allow us to always use single quotes around all counters so they
are sent in as literals and will not be expanded because of double quotes.
> found better way to allow for unicode apostrophe u'\u2019'

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
- docs/body.md
Fixes ZPS-2015
the output of each disk object was being overwritten until the very last one.
need to print out each object as we build it
> Move output to innermost loop to get all disk info

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testWinCluster.py
- docs/body.md
Fixes ZPS-1932
After a failover occurs, modeling will not remove existing disk components for a node
> send empty disk object maps to nodes to remove duplicates

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
- docs/body.md
Fixes ZPS-2015
the MSCluster_Resource WMI class does not contain the Id and OwnerNode
attributes on 2008.  They're only on 2012, 2016+.  get-clusterresource
will return a class that does contain the required attributes.  we'll
keep our wmi loops however as this seems to be a more accepted method
of finding cluster disks and their sizes.
> Use get-clusterresource so we can get the id/ownernode on 2008

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testClusterDataSource.py
- docs/body.md
Fixes ZPS-2416
Need to be sure to pull the state from the wmi class because we're using
it to determine state, not get-clusterresource.  Also, it's redundant to
model disks in the resources.
> Pull cluster disk state from wmi class

- ZenPacks/zenoss/Microsoft/Windows/device_classes.yaml
- docs/body.md
Fixes ZPS-2434
add usedFilesystemSpace__bytes alias, along with inputOctets__bytes, outputOctets__bytes, memoryAvailable__bytes for platform based reports
> Restore usedFilesytemSpace__bytes alias

- ZenPacks/zenoss/Microsoft/Windows/patches/platform.py
- docs/body.md
Fixes ZPS-2421
Reverting monkeypatch of platform code as unnecessary after talking to @cluther 
"What I’m thinking is that the platform DeviceFacade.getTemplates should be fixed to only use the `in object.zDeviceTemplates` check if `not isinstance(object, Device)`. I say this because `obj.getRRDTemplates()` has a very different meaning when called on device classes vs. devices.
This way it could be fixed generically, not have to be patched in Windows, and be applicable to other ZenPacks using the same template binding strategy as Windows."
> Revert change from previous commit

- ZenPacks/zenoss/Microsoft/Windows/datasources/IISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/IIS.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testIIS.py
- docs/body.md
Fixes ZPS-2555
We were setting is_iis to True no matter what.  We should only set it
to True if we find IIS sites.  Also need to catch an exception that
could occur in the IISSiteDataSource
> If no site info found, set is_iis to False

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- docs/body.md
Fixes ZPS-2645
Should have been using this method in the first place as getHostByName
could hit dns
> getHostByName will not work in ZaaS, pull from device

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- docs/body.md
Fixes ZPS-2644
Having more databases can cause our modeler to take longer to complete.
Let's convert our single command to be run via the long command so we
can wait until it finishes.  Monitoring will also be affected as we are
looping through all dbs to pull metrics
> Use long command to get sql server databases

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- docs/body.md
Fixes ZPS-2717
When we get an immediate error from starting the get-counter command,
we should go ahead and return.  If we do not, this is leaving the ds
in a running state and contributes to missed runs.  looks to be due to the
timing of how long it takes for the error to come back from trying to get data.
The task does eventually finish, but, in the meantime, it appears as a Running_Task
and then eventually a Missed_Run.
> get_data should return if datasource is in STOPPED state

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- docs/body.md
Fixes ZPS-2741
Regex was not catching names with symbols, e.g. Microsoft-Windows-Backup or
Microsoft-Windows-PowerShell/Operational
> Account for event logs with '-' and/or '/' in name

- ZenPacks/zenoss/Microsoft/Windows/migrate/RemoveExchangeDuplicates.py
- docs/body.md
Fixes ZPS-2197
There are two duplicate datasource/points in the exchange zenpack.  different names for the same counter.  these are overriding the base windows exchange templates
> Remove duplicate exchange dps, graphs, thresholds

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
Every time PerfmonDataSourcePlugin.start() is called, it leaks a
LoopingCall. This eventually results in memory leakage, and steady
growth of CPU usage by zenpython over time until it is restarted.
Fixes ZPS-2176 and ZPS-2480.
> Stop endless creation of LoopingCalls

- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- docs/body.md
Fixes ZPS-3056
EventLogDataSource is correct and we will continue to send to the /Unknown event class.
Also updated event datasource section so that we explain the max age field and how it only is used once.
> Removed default event class for some datasources

- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/IISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/PortCheckDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testIISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testPortCheckDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testShellDataSource.py
Fixes ZPS-3056
Send onError type events to /Status.  no need to eventClassKeys or using datasource eventclass
> Send onError events to '/Status' for datasources

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Interfaces.py
- ZenPacks/zenoss/Microsoft/Windows/tests/data/Interfaces_process_194131.pickle
- ZenPacks/zenoss/Microsoft/Windows/tests/testInterfaces.py
Fixes ZPS-3100
If no WMI data is returned, but there is powershell data, we are sending back an empty relationship map, which blows away existing model.  We should try to keep existing components, so we'll issue a warning stating incomplete modeling results and return nothing.
Added unit test to confirm
> Account for no WMI data, but successful ps query

- ZenPacks/zenoss/Microsoft/Windows/datasources/ProcessDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testProcessDataSource.py
- docs/body.md
Fixes ZPS-3116
If we're missing wmi data, raise exception.  added unit test
> Check for missing wmi data

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testPerfmonDataSource.py
Fixes ZPS-2383
This will double check that counters are actually corrupt so that we don't have a false negative.  For example, get-counter could succeed in showing a sample for a counter, but there could be something written to stderr.  for now, let's just log the error as debug.  Added unit test
> double check corrupt counters

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-3123
Change ClusterNodeObject from Device to Windows Device so that it is differentiated from the cluster device.
> Change Device label so it's not confusing

- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
Fixes ZPS-3143
If freespace is -1, this means there are no partitions and freespace would have no meaning.  don't write the datapoint and it will show as N/A on a graph and won't get hit by any threshold
> don't write invalid datapoint

- ZenPacks/zenoss/Microsoft/Windows/ClusterDisk.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-3149
Use bytesString as renderer for freespace and be sure to pull the state_state datapoint for disk state
> Fix display of state, freespace

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
Fixes ZPS-2712
Be sure to issue an event for bad username/password for local auth when starting the perfmon command.  Also, let's not show the traceback in the log.  could cause confusion
> issue bad username/password event

- docs/releases.md
- docs/windows.html
Show only last 3 releases.  only need to show that we're compatible with Zenoss.  core and res mgr are implied.  release section was not creating correctly either.  add space between colon and text so that line items show
> clean up releases, show less redundant info

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testOperatingSystem.py
- docs/body.md
Fixes ZPS-3227
None is a valid value for PrimaryOwnerName of Win32_ComputerSystem or RegisteredUser of Win32_OperatingSystem, so we were trying to perform a strip() on None.  Added unit test to account for this situation.  unit test also found problem with regex sub on osCaption.
> Be sure we have a string before strip()

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testShellDataSource.py
- docs/body.md
Fixes ZPS-3302
For now, apply a simple b64 encoding to obfuscate the password sent into the sql scripts for modeling/monitoring.
> Apply simple obfuscation of sql password in queries

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- docs/body.md
Fixes ZPS-3392
By using SSPI for Windows Authentication, we can avoid passing in the windows user password altogether.  Also it will cut down on the number of logons/logoffs when getting job/db properties.  we'll recommend using windows auth in readme because Microsoft does also.  centralize the connection part of the script because it's used in modeler plugin and shell datasource.
> use sspi in connection string for fewer logins

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- docs/body.md
Fixes ZPS-3997
errorMessage was uninitialized, causing an errback and self.state was never changed to STOPPED.  state was stuck in the STARTING state and could never be brought out of it due to this.  updated event summary and sending clear events now
> fix uninitialized local variable

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Interfaces.py
- docs/body.md
Fixes ZPS-3902
2012 and up may have \network interface\ counter objects, but we can't rely on that.
> use \Network adapter counter object for 2012 and up

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Interfaces.py
Fixes ZPS-3902
we should look at the version info, not just the name.  we now have server 2016.  next will be 2020, etc.
> future proof counters2012 query

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- docs/body.md
Fixes ZPS-3581
for any given device or device class, if zWinPerfmonInterval is different for one or more perfmon datasources, then data is popped off the persister before it's ready and will not populate the db correctly.  we can create a unique id to store data using the device id and cycle time so that all the data is returned correctly
> allow same device to have multiple cycletimes for counters

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- docs/body.md
Fixes ZPS-3517
if the PSModulePath is wrong or contains a UNC path, powershell modules could fail to load and we'd see errors about simple powershell cmdlets not working.  this will raise an event giving user info to be sure their path is right.  also documented this in a troubleshooting section
> raise event for possible powershell config issue

- ZenPacks/zenoss/Microsoft/Windows/device_classes.yaml
[ZPS-2152](https://jira.zenoss.com/browse/ZPS-2152?filter=-1&jql=resolution%20%3D%20Unresolved%20AND%20assignee%20in%20(currentUser())%20order%20by%20updated%20DESC)
**Issue:** Windows - "Time" graph for File Systems and Hard Disks is confusing
**Comment:** Works for me after reinstalling the zenpack
> "Time" graph for File Systems and Hard Disks is confusing

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- docs/releases.md
Fixes ZPS-3377
when receive fails on a device reboot, we were restarting the entire process.  this is unnecessary and the reason we see tons of error messages.  we will just wait until the next cycle to start collection over.  handling certain error messages and sending them to debug with an explanation that they are possibly due to a device reboot.
updated releases sections for proper formatting of releases
> do not restart() on receiveFail

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- docs/body.md
Fixes ZPS-4184
Since we are grabbing the ip address of the instance, we should also store it in case we can't auto-discover the node.
> add owner_node_ip property to sql instance

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
because regex are multiline incontinent
zps-3484
> support for multiline

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
- docs/body.md
Fixes ZPS-4272
customer cluster modeling was taking longer than 60s so allow the timeout to be increased
> allow cluster datasource to run longer

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Interfaces.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testInterfaces.py
- docs/body.md
Fixes ZPS-4149
no TeamName option was set on the adapter so we were unaware these were teamed.  if Speed is None, then we won't monitor them.  Updated unit test to account for this
> do not monitor individual NICs in a team

- ZenPacks/zenoss/Microsoft/Windows/Device.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/RemoveExtraClusterPlugins.py
- docs/body.md
Fixes ZPS-4300
Remove the unnecessary append of the WinCluster plugin to the zCollectorPlugins property.  Devices in the cluster class already will be using this plugin.  added a migrate script to remove extra ones already added.
> remove unnecessary append

- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- docs/body.md
Fixes ZPS-3424
need to use prepId to make sure that the service name and id match correctly.  also added a blurb to krb troubleshooting about spns.
> make sure service id matches correctly

- ZenPacks/zenoss/Microsoft/Windows/BaseDevice.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- docs/body.md
Fixes ZPS-4422
we should not be sending maps that will slow down the system this way.  perhaps a simple datasource that will perform this operation instead.
reverting this PR:  https://github.com/zenoss/ZenPacks.zenoss.Microsoft.Windows/pull/1035
> revert change that sends maps to zenhub from perfmon

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- docs/body.md
Fixes ZPS-4473
if we are failing to receive, this can be due to many factors.  could be a simple OperationTimeout, which means counters have not reported, so we will retry.  on a timeout error we should retry to receive.  anything else we will try to stop the command and reset ourselves into a better state.
> attempt to stop and reset on receive failures

- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/data/ClusterDataSourcePlugin_onSuccess_210137.pickle
- ZenPacks/zenoss/Microsoft/Windows/tests/testClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- docs/body.md
Fixes ZPS-4612
Cluster shared volumes are not returned from get-clusterresource so we can't get disk state that way.  we can map the state to our disk states however.  captured customer data in a pickle to create a unit test to ensure we are setting the correct state and updating freespace
> account for cluster shared volumes freespace and status

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- docs/body.md
Fixes ZPS-4703
Test-Connection was not giving us the correct ip address for the ownernode.  ping will so we can regex it out of the ping results.
> use ping to get ip address of owner node

- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Interfaces.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
- docs/body.md
[ZPS-4927](https://jira.zenoss.com/browse/ZPS-4927)
Get-WmiObject has been deprecated in Windows PowerShell Core (6x), Replaced with Get-CimInstance that works with both Windows PowerShell and Windows PowerShell Core
> ZPS-4927: replace a deprecated Get-WmiObject

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- docs/body.md
fixes ZPS-4888
sql server can be active on node other than the current master.  this change will allow for contacting the correct device
> allow for cluster sql instance perfmon

- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
fixes ZPS-5552
get-ciminstance returns different object than get-wmiobject so we need to get associated disks and partitions differently
> updates for using get-ciminstance in cluster datasource

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testOperatingSystem.py
- docs/body.md
fixes ZPS-5253
on openstack, a windows vm may not contain any info on the system enclosure.  we will end up with an empty result and can cause and IndexError trying to get the results out.  added unit test to account for this
> test for empty Win32_SystemEnclosure results

- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- docs/body.md
Fixes ZPS-5755
get-ciminstance only available in powershell v3+.  we need to account for that until support for windows 2008 is EOL.  2012 and up will default to using newer versions.
> powershell 2 does not support get-ciminstance

- ZenPacks/zenoss/Microsoft/Windows/tests/test_dynamicview.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Specifying impact relationships under the impacts/impacted_by fields and
the dynamicview_relations field results in Impact having to execute the
relationship-finding code twice. It's only necessary to use
dynamicview_relations to get the relationships into Dynamic View and
into Impact.
Fixes ZPS-5778.
> eliminate duplicate impact relationships

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
DynamicView.model.adapters.DeviceRelationsProvider and
SimpleComponentRelationsProvider already provide the impact
relationships being taken out in this commit.
Fixes ZPS-5778.
> remove more duplicate impact relationships

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testOperatingSystem.py
- docs/body.md
Fixes ZPS-5820
if we're not getting wmi data, then let's allow the modeler to finish with Unknown attributes
> allow OperatingSystem to finish modeling

- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
- docs/body.md
fixes ZPS-5835
the name field may not contain cluster group or sql server.  this will send the remodel event when we see that the owner node has changed for any cluster service/role
> remove unecessary check for matching name

- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
- docs/body.md
fixes ZPS-5582
when modeling, we will skip getting the disk number for win 2008 devices.  determining a workaround with wmi objects is not a useful endeavor because there are no direct associations.  also, when monitoring, we only need to worry about getting the id, freespace, and state of the csv.  we should have also been ignoring the csvs when getting 'Physical Disk' resources.  updated doc to indicate that an no disk number will be reported for the csvs on win 2008
> take into account lack of get-disk/get-partition on win2008

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
Per ZPS-6861: this PR is for better handling of "invalid selectors" error:
- move it up into "elif '500' in e.message:" block
- set retry=False (this message indicates loss of connection to the device possibly due to reboot or restart of the WinRM service)
This should avoid a retry loop where we make thousands of connections to a single device when we hit the "invalid selectors" 500 error.
> ZPS-6861: better handling of "invalid selectors"

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testOperatingSystem.py
- ZenPacks/zenoss/Microsoft/Windows/txwinrm_utils.py
Fixes ZPS-6244
When we had an insufficient responce from server,
original value of `snmpSysName` might be replaced with
'Unknown' string. So we check if we have anything from
the previous modeling.
> Fix issue with Sysname property on device level

- ZenPacks/zenoss/Microsoft/Windows/WinSQLAvailabilityGroup.py
- ZenPacks/zenoss/Microsoft/Windows/WinSQLAvailabilityGroupHostedObject.py
- ZenPacks/zenoss/Microsoft/Windows/WinSQLInstanceHostedObject.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/device_classes.yaml
- ZenPacks/zenoss/Microsoft/Windows/event_classes.yaml
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testWinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Implements ZPS-7435.
* Add Availability group component.
* Add monitoring, incremental modeling and events for Availability group component.
* Add WinSQLInstance(winsqlavailabilitygroups) 1:M (winsqlinstance)WinSQLAvailabilityGroup relation.
* Add Availability replica component.
* Add non-containing realtion to WinSQLInstance and containing relation to WinSQLAvailabilityGroup.
What were done described more detailed in Jira comments:
* [Availability group component](https://jira.zenoss.com/browse/ZPS-7363?focusedCommentId=183051&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-183051)
* [Availability replica component](https://jira.zenoss.com/browse/ZPS-7435?focusedCommentId=183521&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-183 …
> Add Availability Group and Replica components

- ZenPacks/zenoss/Microsoft/Windows/migrate/UpdateAlwaysOnRelations.py
- setup.py
Fixes ZPS-7466.
* Add migration script to update pre 3.0.0 components which have new Always On relations: 'OperatingSystem', 'WinSQLInstance'.
* Bump ZenPack version to actual release one.
> Add migration script to update AlwaysOn relations

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Implements ZPS-7462.
* Send empty maps by default for AG contained components: Availability Replicas, Availability Listeners.
* Small code refactoring.
> Send empty maps by default for AG components

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Implements ZPS-7491.
* Send empty maps by default for Always On SQL Instance contained components: Databases.
> Send empty maps by default for Instance cont cmp

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
Implements ZPS-7495.
Add events for Availability Group properties: Synchronization Health, Quorum State.
> Add events for some Availability Group properties

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
Implements ZPS-7515.
Default SQL Instances are named after their Windows nodes. Need to take this
into consideration when operating with theirs original names.
> Get proper Default instance original name

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Fixes ZPS-7507.
Remove Availability Replicas pre-collection from Windows registry, as data from it
is unreliable and volatile.
Described this case in [Jira comment](https://jira.zenoss.com/browse/ZPS-7507?focusedCommentId=186089&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-186089)
> Remove Availability Replicas pre-collection

- ZenPacks/zenoss/Microsoft/Windows/Device.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-7514.
* Add DynamicView & Impact relations from Windows node (/Server/Microsoft/Windows device) to its Cluster device.
* Add DynamicView & Impact relations from Cluster device to its Node component.
> Add DVI relations from Windows to Cluster device

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/txwinrm_utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-7526.
* Remove Cluster state property from Availability Group component as it relevant to Cluster Device.
* Remove Failover mode property from Availability Group component as it relevant to Availability Replica component.
In [Jira comment](https://jira.zenoss.com/browse/ZPS-7526?focusedCommentId=186573&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-186573)  described what has made.
> Remove Cluster state prop from Availability Group

- ZenPacks/zenoss/Microsoft/Windows/actions.py
Fixes ZPS-5995.
Adjust value of Device's kerberos_rdns property to its type.
> Adjust value of kerberos_rdns prop to its type

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testPerfmonDataSource.py
Fixes ZPS-5967.
Retry 'Class not registered' and 'Illegal operation attempted on a registry key that has been marked for deletion' Windows errors for Perfmon datasource plugin
as these errors frequently occurs if new service account trying to use resources after previous was log off.
This may occurs for to quick shell reinitialization.
Also add unit test.
> Retry two 500 error for Perfmon datasource plugin

- ZenPacks/zenoss/Microsoft/Windows/WinSQLAvailabilityGroup.py
- ZenPacks/zenoss/Microsoft/Windows/WinSQLAvailabilityReplica.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/device_classes.yaml
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Implements ZPS-7655.
AO Replicas performance counters are placed on other nodes unlike other counters. Need to pick up right Windows node for this type of counters.
> Pick the right node for Replicas performance counters

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-7867.
Add a zProperty in order to stop monitoring MSSQL databases
in STANDBY and RESTORING statuses.
> Stop monitoring databases in specific statuses

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
Fixes ZPS-7815.
Change WMI database queries for OperatingSystem modeller plugin
in order to reduce amount of data and prevent timeout exception
> Fix WMI queries in OperatingSystem modeler plugin

- ZenPacks/zenoss/Microsoft/Windows/txwinrm_utils.py
Potential fix for ZPS-8015, (if not, then this fixed another undiscovered bug)
The Windows ZenPack tries to be fancy by using 'windows_user', 'windows_password', and 'windows_servername' instead of the zProperties.  however, because these are method-properties of the base object and not zProperties defined in the yaml, zenoss-prodbin, can get really confused and not know what values to put into a proxy device. For CZ, zenmodeler and prodbin's ZenHub/service/ModelerService.py was not providing all the required values to complete a connection.
> retaining required zProp values

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/txwinrm_utils.py
updating winzenpack for handling method parameters values for zen modeler and zenpython.
fix for zps-8015
> fix for zps-8015, adding support for method values in dsconf

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Services.py
Fixes ZPS-8115.
Stripped zWinServicesGroupedByClass zProperty
from spaces and newlines, etc.
> Strip zProperty from spaces and newlines

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
Implements ZPS-8277.
xml.dom.minidom package has been used instead of obsolete package.
> Remove dependency on obsolete PyXML package

- ZenPacks/zenoss/Microsoft/Windows/ClusterResource.py
- ZenPacks/zenoss/Microsoft/Windows/__init__.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testWinCluster.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- docs/body.md
Implements ZPS-8412.
Added new zProperty zWinClusterResourcesMonitoringDisabled which is responsible for Windows Cluster Resource monitoring disabling according to its corresponding Windows Service startup type. Added is_winservice_disabled attribute for Cluster Resource component to determine whether the corresponding WinService is disabled. It finds the specific WinService by its name or by new winservice attribute that stores the value of the corresponding WinService ID if the Cluster Resource type is "Generic Service". Added and fixed unit tests.
Added documentation.
> Do not monitor disabled Windows Cluster Resources

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
Implements ZPS-8666.
Added a log message when misconfigured counter is
in the Perfmon datasource collection.
> Add a log message for misconfigured counter

- ZenPacks/zenoss/Microsoft/Windows/migrate/UpdatezWinServicesGroupedByClass.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Adding additional per-user Windows Services that were omitted from the Microsoft KB listing them. I'm reusing the same migration script but with a version bump.
ConsentUxUserSvc - Consent User Experience User Service.
cbdhsvc - Clipboard User Service
CredentialEnrollmentManagerUserSvc - Credential Enrollment Manager User Service in Windows.
UdkUserSvc - Undocked Dev Kit User Service
> ZPS-8740 - Add Additional Per-User Windows Services

- ZenPacks/zenoss/Microsoft/Windows/handlers.py
Fixes ZPS-8862.
There is no "type" attr available for the job object. We will compare "name" attr with an actual name of the job.
> Fix ReindexWinServices job execution

- ZenPacks/zenoss/Microsoft/Windows/device_classes.yaml
- ZenPacks/zenoss/Microsoft/Windows/migrate/RemoveSoftwareModelerPluginFromDefaults.py
Implements ZPS-8911.
Removed the 'Software' modeler plugin from the '/Server/Microsoft/Windows' device class defaults. Added a migration to delete the plugin for the already created devices.
> Remove ‘Software’ modeler plugin from the defaults
