- README.mediawiki
> Readme updates

- ZenPacks/zenoss/Microsoft/Windows/FileSystem.py
missing label keyword causes xml read error
> Fixes ZEN-16064

- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ZenPacks/zenoss/Microsoft/Windows/__init__.py
Add z prop so users can monitor all services with Auto startmode
> Fixes ZEN-15834

- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
Move to debug log instead of info.  This message appears for every monitored service on every device.
> fixes ZEN-16420

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Software.py
Some software is listed underneath the HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall registry key instead.  We need to look in both locations.
> Fixes ZEN-16574

- README.mediawiki
Added hyperv note.  Also, minor changes around setspn.
> Fixes ZEN-16170

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
We were ignoring the max_age input from the beginning
> Fixes ZEN-16564

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
Need to handle attributeerrors.  these occur when user does not have correct permissions on the target.
> Fixes ZEN-16799

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
Reverts zenoss/ZenPacks.zenoss.Microsoft.Windows#333
> Revert "Fixes ZEN-16799"

- ZenPacks/zenoss/Microsoft/Windows/Device.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
update zDeviceTemplates for bind templates.  Also do not bind exchange template when no exchange installed
> Updates ZEN-17059

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
Add clear event for custom command
> Fixes ZEN-17192

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
DCDiag could be installed on win 2003 so let's check for the ntds service to be present instead.
> Check for NTDS instead of DCDiag

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
Let's reset the default just in case it was set previously
> Set default value to False

- README.mediawiki
Document centos5 limitation and add other documentation updates.
> Document ZEN-16546

- ZenPacks/zenoss/Microsoft/Windows/browser/resources/js/global.js
- ZenPacks/zenoss/Microsoft/Windows/datasources/PortCheckDataSource.py
Do not allow for user to add same port twice.
Also needed to add Windows PortCheck datasource type
> Fixes ZEN-17299

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/migrate/MigrateIISGraphs.py
Need to remove existing graph definition.
Also updated readme
> Update to ZEN-17045

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
FilterHashTable is not valid for windows 2008.  only for 2008 R2 and above
> Fixes ZEN-17319

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
We need to always update the last read so that we truly only get the events from the last interval.  
Also updated the readme
> Fixes ZEN-17366

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Improve modeling performance by running one powershell script per instance instead of 3.  SQL Server has a max of 50 instances so at most we'll be running 50 shells concurrently.  Also remove zDBInstances requirement.  We'll still honor it for backwards compatibility.
> Fixes ZEN-17669.

- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
somehow local settings got saved into xml
> remove unnecessary props in xml

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Need to check for sql user names and allow for default user name using windows auth
> Fixes ZEN-17691

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
Need to have backwards compatibility with zDBInstances.  We should also allow for users to enter different credentials for different instances.  Fixed default mssqlserver instance also.
> Fixes ZEN-17683

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
allow mixed login types for specified instances
> Fixes ZEN-17691.

- ZenPacks/zenoss/Microsoft/Windows/utils.py
Fixed so that if zDBInstances is a list of sets then we can recognize that also.
> Fixes ZEN-17712

- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
test datasource accidentally made it into the objects.xml
> Fixes ZEN-17893

- README.mediawiki
Added documentation for non-admin(LPU) users and exchange monitoring.
> Fixes ZEN-11808 and ZEN-11847

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
> Fix leak of irrelevant points into shell parsers.

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
Fix powershell to test if db is accessible so we don't get exception.  If inaccessible then show db as offline with whatever severity is used for the datasource.  send clear events if it is accessible
> Fixes ZEN-18234

- ZenPacks/zenoss/Microsoft/Windows/migrate/MigrateThresholds.py
- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
Remove bad thresholds.  add one each for memory, cpu, paging file.
> Fixes ZEN-16024

- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ZenPacks/zenoss/Microsoft/Windows/browser/resources/js/global.js
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
Change start mode selection from drop down box to a check box group so users can choose 2 of the three start modes.
> Fixes ZEN-18006

- ZenPacks/zenoss/Microsoft/Windows/WinSQLJob.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/info.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
- ZenPacks/zenoss/Microsoft/Windows/utils.py
This includes initial changes into develop branch in pull request 404, https://github.com/zenoss/ZenPacks.zenoss.Microsoft.Windows/pull/404, which incorporated monitoring sql instances.
We also need to monitor jobs
> Fixes ZEN-18680

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
> Fixes Zen-19235

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
needs to be an instance variable, not a class var
> Fixes ZEN-19236

- ZenPacks/zenoss/Microsoft/Windows/ClusterDevice.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
get ip addresses from the collector instead of master.  this is mainly a problem for zaas as the masters will not usually have access to the customers network.
> Fixes ZEN-19085

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
Need to use prepare_instance on the name
> Fixes ZEN-19282

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
- yaml/WinService.yaml
Invalid class name.  yaml is not used, but doesn't hurt to have it in there
> Fixes ZEN-19284

- ZenPacks/zenoss/Microsoft/Windows/WinSQLDatabase.py
- ZenPacks/zenoss/Microsoft/Windows/info.py
- ZenPacks/zenoss/Microsoft/Windows/interfaces.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Fixes https://jira.zenoss.com/browse/ZEN-17630
> ZEN-17630 Model "IsSystemObject" and "RecoveryModel" for MSSQL Databases

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
Fixes https://jira.zenoss.com/browse/ZEN-18835
> ZEN-18835: Microsoft Windows - Cluster event is in Unknown class

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
Fixes https://jira.zenoss.com/browse/ZEN-18836
> ZEN-18836 Microsoft Windows - Database event is in Unknown class

- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
need to be returning service['eventClass'], not looking in config.datasources.
> Fixes ZEN-19452

- README.mediawiki
> update the readme

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
Fixes https://jira.zenoss.com/browse/ZEN-19292
> ZEN-19292: Custom command - powershell - Not accepting double quotes

- ZenPacks/zenoss/Microsoft/Windows/tests/testFileSystems.py
Fixes https://jira.zenoss.com/browse/ZEN-19829
> Added fake property to FS  object  to pass tests

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
Update defaults for cycletime, query.  add default for eventClass.  remove unused strategy
> Fixes ZEN-13471

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/migrate/RemoveBadClusterDS.py
- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
Need migrate script to replace existing datasources.  readme updates
> Fixes ZEN-174707

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
Need to replace "s in string with \" so that the quotes make it through to powershell
> Replace "s with \"

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
> Fixes ZEN-20214

- ZenPacks/zenoss/Microsoft/Windows/analytics/README.txt
Fixes https://jira.zenoss.com/browse/ZEN-19992
> ZEN-19992: readme added to analytics directory

- README.mediawiki
Fixes https://jira.zenoss.com/browse/ZEN-19995
Installation instruction has been clarified and agreed with Analytics administration guide.
> Installation instruction for analytics-bundle.zip has been clarified

- ZenPacks/zenoss/Microsoft/Windows/WinSQLJob.py
- ZenPacks/zenoss/Microsoft/Windows/info.py
by default do not monitor if the job is disabled
> Fixes ZEN-20287

- ZenPacks/zenoss/Microsoft/Windows/WinSQLJob.py
- ZenPacks/zenoss/Microsoft/Windows/info.py
> don't need usermonitor property

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/__init__.py
- ZenPacks/zenoss/Microsoft/Windows/patches/__init__.py
- ZenPacks/zenoss/Microsoft/Windows/patches/platform.py
> Fix modeling of IPv6 host addresses.

- README.mediawiki
There's nothing we can really check during monitoring.  We will add information to the wiki
> Fixes ZEN-20542

- README.mediawiki
Added not about IISAdmin service running.  Also fixed formatting on a few other notes
> Fixes ZEN-19300

- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
> Add devtype for /Server/Microsoft/Cluster.

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
.NET 4.0 isn't recognized by Powershell 2.0, so .NET 2.0 still appers in the clr.  reverting for customer until we can find better solution.
> Revert previous changes to this branch

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
fixes https://jira.zenoss.com/browse/ZEN-20931
fix copy/paste error.
> Fixes ZEN-20931

- README.mediawiki
Typo fixes for https://jira.zenoss.com/browse/ZEN-20940
> Fixes ZEN-20940

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
Reworked powershell script for efficiency and to avoid Exceptions.  Also $diskVolume and $diskvolume are the same variable in powershell so best to avoid reassigning it.  PEP8 stuff too
> Extra Fix for ZEN-21242

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
cherry-picking this commit. it was accidentally left out of the initial 2.5.1 release.
> Update for service monitoring

- ZenPacks/zenoss/Microsoft/Windows/WinService.py
part ii of service update cherry-pick
> check for service name only

- ZenPacks/zenoss/Microsoft/Windows/actions.py
> Fixes ZEN-21272

- ZenPacks/zenoss/Microsoft/Windows/modeler/WinRMPlugin.py
Set status in WinRM, not in Ping
> Fixes ZEN-21270

- ZenPacks/zenoss/Microsoft/Windows/modeler/WinRMPlugin.py
We should show event for all modeling errors.
> Fixes ZEN-16195

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
for db monitoring, value will only be a single int.  not a list.
> Fixes ZEN-22476

- README.mediawiki
Document missing WinRMRemoteWMIUsers__ group issue.
> Fixes ZEN-22566

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
> Fixes ZEN-22487

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/Device.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/WinRMPingDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/WinRMPlugin.py
- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
Create event class for /Status/Winrm/Ping
> Fixes ZEN-22407

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
> fix possible IndexError

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
> don't set query_error.  unable to use powershell query

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/IISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ProcessDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/CPUs.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/FileSystems.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/IIS.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Interfaces.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Processes.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Routes.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Services.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Software.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
@save will dump out arguments to functions.  Users can then zip them up
and send to us so we can work with their data.
> Added @save decorator for help in diagnosing customer issues

- README.mediawiki
Fixes ZEN-22992
Update the wiki to show what requirements we need a user to have
in order to monitor a Windows device.  Also include changes to
show sql server requirements.  Added table of contents
> Update readme to reflect user account requirements

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Fixes ZEN-23085
Must have been a leftover artifact from testing something.  Removed
log entries
> Do not write out user and pass to log

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/IIS.py
- added method to find associated ApplicationPool objects for IIS Sites
in version 7 of IIS
> Fixes ZEN-21288

- ZenPacks/zenoss/Microsoft/Windows/modeler/WinRMPlugin.py
Fixes ZEN-23049
This may end up mixing the formatting of the strings so we should
keep it consistent
> Be sure not to mix string formatting

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- Only set eventClass if it is manually set to other than "/Unknown", so
that user can use event class mappings
> Fixes ZEN-23024

- ZenPacks/zenoss/Microsoft/Windows/__init__.py
- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
Fixes ZEN-23115
Not sure why this was ever set to WMI since this is the WinRM ZenPack
> Change WMI to WinRM.

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- ensured that EventLogDatasource query attribute is always treated as a
list.
> Fixes ZEN-23156

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- added "get_script" method to handle single or multi-line powershell
script
> Fixes ZEN-22847

- ZenPacks/zenoss/Microsoft/Windows/Device.py
- fixed incorrect logic leading to traceback in getRRDTemplates
> Fixes getRRDTemplates

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testIISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testProcessDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testShellDataSource.py
Fixes ZEN-23326
Send in a Failure so that onError can run.  Also fixed missing quotes.
> Fix unit tests

- README.mediawiki
Fixes ZEN-23228
In order to view db status and counters, user needs to be added
to each database.  Added this to documentation and example of how
to do it using SQL
> Document sql server lpu permissions

- README.mediawiki
replaced broken link with list of severities
> Fixes ZEN-22522

- README.mediawiki
- fixed typographical errors in readme.mediawiki
> Fixes ZEN-23450

- ZenPacks/zenoss/Microsoft/Windows/tests/testProcessDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testServices.py
- fixed unit test failures for TestServiceDataSource,
TestProcessDataSource, TestServices
> Fixes ZEN-23326

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
> Change default cycle time to 300s

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
Fixes ZEN-23228
This will allow the user to only require 'VIEW SERVER STATE' permissions
> Query db counters from master db

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- cleaned up details pane for Interface and FileSystem components
> Fixes ZEN-23648

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
> Give the datasource object to WinCmd for customer parser access

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/info.py
- ZenPacks/zenoss/Microsoft/Windows/interfaces.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Services.py
Fixes ZEN-23761
Was not checking for datasource.enabled attr
Added description back into the details pane
> Add description back in, check for datasource.enabled

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ZenPacks/zenoss/Microsoft/Windows/interfaces.py
add ignore case to regex compile
Change details text to show Manually instead of User
> Readme updates for Windows ZP

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
Better accommodate both templates and service classes
> clean up WinService/ServiceDatasource 

- ZenPacks/zenoss/Microsoft/Windows/Device.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- corrected issues with impact relations and map rendering
> Fixes ZEN-23741

- ZenPacks/zenoss/Microsoft/Windows/tests/testServiceDataSource.py
- update testServiceDataSource to reflect WinService/ServiceDataSource
changes
> Fixes ZEN-23789

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/FileSystems.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
Fixes ZEN-23793
If ZEN-19213 is really an issue then we'll revisit a better solution.
For now we need to show all drives.
> Revert changes from ZEN-19213

- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ensure that monitoring changes get cataloged immediately and that
ServiceDatasource retrieves monitor value from catalog
> Fixed ZEN-23766

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/migrate/ResetClassTypes.py
- Partial fix for ZEN-24401
- Update migrate script to remove any locally set meta_type and
portal_type attributes on target classes
> Fix duplicate "Interfaces" components on Device Status page

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Fixes ZEN-24519
Previously we were assuming that 'master' was the db at pos [0].
Instead this will use the JobServer property of the sql server.
update readme
> Make sure we're finding jobs correctly.

- ZenPacks/zenoss/Microsoft/Windows/Device.py
Fixes ZEN-25564
Added zWinKDC property to the cluster device
> Fixes ZEN-25564.

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- setup.py
Fixes ZEN-24726
Look for 'Check username and password' in error message
> Need to check for bad password in error message to send event

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/IISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ProcessDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/WinRMPingDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
- ZenPacks/zenoss/Microsoft/Windows/utils.py
> Added additional event classes to cover connection errors.

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
> We only need the version for SQL datasources

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/HardDisks.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-479
Added monitoring template of hard disks using perfmon counters
> Add monitoring of HardDisks

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/objects/objects.xml
- ZenPacks/zenoss/Microsoft/Windows/tests/testEventLogDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testIISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testProcessDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
Fixes https://jira.zenoss.com/browse/ZEN-25700
> Added additional event classes and handlers for Kerberos failures.

- ZenPacks/zenoss/Microsoft/Windows/HardDisk.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/HardDisks.py
Fixes ZPS-626
* Make sure Size and Partitions are a number
* Do not monitor if size and partitions is 0
> Account for uninitialized/offline disks

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- Fixes ZPS-569
- Changed threshold to use 10% of available space
> Fix Memory Utilization Threshold (ZPS-569)

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/actions.py
- ZenPacks/zenoss/Microsoft/Windows/txwinrm_utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-82
* Added zProperty for envelope size
* Removed duplicate zWinRMUser property
> Added ability to specify Envelope Size for winrm requests

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Interfaces.py
Fixes ZPS-625
* Uses AssociatorClient instead of powershell
* associators cost less than powershell script
> Use new AssociatorClient instead of powershell script

- ZenPacks/zenoss/Microsoft/Windows/patches/platform.py
Updated fix for ZPS-572 to avoid conflict with fix for ZPS-651
(ZenPackLib)
> Revised fix for ZPS-572

- ZenPacks/zenoss/Microsoft/Windows/BaseDevice.py
- ZenPacks/zenoss/Microsoft/Windows/CPU.py
- ZenPacks/zenoss/Microsoft/Windows/ClusterDevice.py
- ZenPacks/zenoss/Microsoft/Windows/ClusterDisk.py
- ZenPacks/zenoss/Microsoft/Windows/ClusterInterface.py
- ZenPacks/zenoss/Microsoft/Windows/ClusterNetwork.py
- ZenPacks/zenoss/Microsoft/Windows/ClusterNode.py
- ZenPacks/zenoss/Microsoft/Windows/ClusterNodeObject.py
- ZenPacks/zenoss/Microsoft/Windows/ClusterObject.py
- ZenPacks/zenoss/Microsoft/Windows/Device.py
- ZenPacks/zenoss/Microsoft/Windows/FileSystem.py
- ZenPacks/zenoss/Microsoft/Windows/HardDisk.py
- ZenPacks/zenoss/Microsoft/Windows/Interface.py
- ZenPacks/zenoss/Microsoft/Windows/OSProcess.py
- ZenPacks/zenoss/Microsoft/Windows/OperatingSystem.py
- ZenPacks/zenoss/Microsoft/Windows/TeamInterface.py
- ZenPacks/zenoss/Microsoft/Windows/WinIIS.py
- ZenPacks/zenoss/Microsoft/Windows/WinSQLBackup.py
- ZenPacks/zenoss/Microsoft/Windows/WinSQLDatabase.py
- ZenPacks/zenoss/Microsoft/Windows/WinSQLInstance.py
- ZenPacks/zenoss/Microsoft/Windows/WinSQLJob.py
- Removed individual loggers from class files
- Migrated logging calls to self.LOG (ZPL2)
> Migrate to ZPL2 Logging

- ZenPacks/zenoss/Microsoft/Windows/datasources/IISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Make use of the build powershell function in txwinrm.  This will ensure
that we send the powershell script as a single argument
Also, a couple of pep8 updates
> Send in ps script separately for SOAP formatting

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
> Index disk_ids for fast search of harddisk

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
Fixes ZPS-491
* Get datasource for each test to use severity and event class
update readme
> Honor severity for DCDiag data sources

- ZenPacks/zenoss/Microsoft/Windows/modeler/WinRMPlugin.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
Fixes ZPS-715
* if we can't get results from win32_computersystem then there's some
sort of permissions issue
* update link to zenoss.com website instead of wiki
> Change handling of OperatingSystem results

- ZenPacks/zenoss/Microsoft/Windows/tests/testInterfaces.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testOperatingSystem.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testPerfmonDataSource.py
- Fixes ZPS-712
- Updated unit tests to address failures
> Fix Unit Test Failures (ZPS-712)

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- Fixes ZPS-566
- Update EventLogDataSource to generate an event for each failed data
source, so that failures are tracked on a per-datasource basis
> Add event for each failed datasource (ZPS-566)

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Fixes ZPS-660
* Intermediary step to find problem with cluster modeling
> Add debug logging to help with troubleshooting

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/HardDisks.py
> Add log statement showing processing HardDisk results

- ZenPacks/zenoss/Microsoft/Windows/modeler/WinRMPlugin.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
> Add messages about possible envelope size problem

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- Fixes (ZPS-819)
- Created labels and descriptions for all supplied ZProperties
- Requires ZenPackLib 2.0.2
> Add label and description to zWinRM properties (ZPS-819)

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
Fixes ZPS-516
* Also make log messages more descriptive to know which plugin is running
> Send event when unsuccessfully starting get-counter command

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
> Fix tales expression for counters

- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/RemoveWinRMServices.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/ResetClassTypes.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- Fixes ZPS-762
- Rebase WinService on ZPL proxy class
- Migrated class properties to YAML
- Set dependency on ZenPackLib 2.0.2
> Fix Service Status Display (ZPS-762)

- README.mediawiki
> Update readme to warn about indexing jobs

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
> Missing instance_name property

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/txwinrm_utils.py
> Allow ports 80/443 to be used for winrm

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- Current YAML conversion did not preserve Graphs and GraphPoint
sequence, which may lead to undesirable display
> Re-sequence graphs and graphpoints

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/WinService.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/RemoveWinRMServices.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/ResetClassTypes.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- setup.py
- ZenPackLib 2.0.2 contains fixes for various issues, so updating
dependency so fixes are included here
> Update dependency on ZenPackLib to 2.0.2 and merge related fixes

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- Fixes ZPS-819
- Added description
> Updated description for zWinRMKrb5includedir (ZPS-819)

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/modeler/WinRMPlugin.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
Fixes ZPS-835
* Add 2014, 2016 versions to the load assembly function
* Add extra error events to know what may have gone wrong during modeling
> Add support for SQL Server 2014, 2016

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/HardDisks.py
Fixes ZPS-816
* Also removed redundant log message
> Handle Exception

- ZenPacks/zenoss/Microsoft/Windows/info.py
Use isMonitored() instead as it checks the catalog instead.
> We should be calling isMonitored() instead of monitored()

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- Fixes ZPS-752
- Fixes ZPS-754
- Updated attributes of dummy datapoint config to be platform dependent
> Fix ShellDataSource status datapoints (ZPS-752)

- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/info.py
- ZenPacks/zenoss/Microsoft/Windows/interfaces.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-846
* Status should show if a service is running or stopped
* Events will show if there is a change
* Subclass schema.WinServiceInfo, schema.IWinServiceInfo  also
* Fix datapoints to work with 5.x metrics
* moved get_dummy_dpconfig to utils
* rrdPath is a string and will never be a dict
> Change the the meaing of Status for Windows Services

- ZenPacks/zenoss/Microsoft/Windows/txwinrm_utils.py
> Update error message

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/HardDisks.py
> Check if SerialNumber is empty

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
> Make version a string, not int

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/__init__.py
- ZenPacks/zenoss/Microsoft/Windows/handlers.py
Fixes ZPS-820
* Set zp flags during ZenPack install/remove so that we do not
kick off a reindexing job
* Update readme a bit also
> Fix attribute error.  Do not run during zp install/removal

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/IIS.py
Fixes ZPS-719
* Update docs to make sure users know to install scripts and tools
* Add event/warning log to let users know how to fix missing IIS results
> Make IIS detection more friendly

- README.mediawiki
> Add more helpful information on using zWinRMKrb5includedir

- ZenPacks/zenoss/Microsoft/Windows/ClusterDevice.py
- Fixes ZPS-857
- corrected issues in "all_clusterhosts" method
> Fix Tracebacks in Cluster Host DynamicView (ZPS-857)

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- Set YAML "remove" to "true" for provided device classes
> Remove Device Classes when ZenPack removed (ZPS-914)

- README.mediawiki
> Update readme with troubleshooting tips

- ZenPacks/zenoss/Microsoft/Windows/WinService.py
Fixes ZPS-916
Service is being indexed before fully modeled
> Return False if Service is not fully modeled

- ZenPacks/zenoss/Microsoft/Windows/WinSQLDatabase.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/WinRMPlugin.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-920
* Use statuses from Microsoft https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.databasestatus.aspx to send events for db status
* Scrape events instead of using a datapoint to display status
> Update database status to be more informative

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/HardDisks.py
> Set product key with model, manufacturer

- README.mediawiki
> Inform user to use zWinRMLocale property for other languages

- README.mediawiki
> Add documentation for LPU to have access for IIS

- ZenPacks/zenoss/Microsoft/Windows/Device.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
> Add dynamic/dependency/impact view for HardDisks

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Interfaces.py
> standardize instance name

- README.mediawiki
Fixes ZPS-505
Describes the impact relations for Windows Devices
> Update the service impact relationships in documentation

- README.mediawiki
Fixes ZPS-588
Add further explanation on the use of zWinRMServername property
> Update README for zWinRMServerName

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Fixes ZPS-944
Set wide shell width so that lines do not wrap around
> Set wide shell width in case of long db names, cluster also

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/__init__.py
Fixes ZPS-945
We are not going to advertise localization support
> Removed references to localization support

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/jobs.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/ResetClassTypes.py
Fixes ZPS-959
Halt installation if zenjobs is running
> Move reset class types to a job

- ZenPacks/zenoss/Microsoft/Windows/Device.py
> Check both ip and clustername to make sure device doesn't exist

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-942
* Allow for Paused state of service.  Service may be ok if it's just paused with no need to alert
update readme
> Add Paused as a valid WinService status

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
> replace double quotes with escaped double quote

- ZenPacks/zenoss/Microsoft/Windows/tests/createdevice.py
- analytics/resources/public/Microsoft_Windows_ZenPack/.folder.xml
- analytics/resources/public/Microsoft_Windows_ZenPack/Microsoft_Cluster_Domain.xml
- analytics/resources/public/Microsoft_Windows_ZenPack/Microsoft_Cluster_Domain_files/schema.xml.data
Fixes zps-953
* Add cluster domain xml
* Update create cluster device with sql servers
* Update domain descriptions
> Add cluster domain, descriptions

- ZenPacks/zenoss/Microsoft/Windows/modeler/WinRMPlugin.py
> Check for html in response for compatibility port use

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
Fixes ZPS-831
also add more logging info for dcdiag and custom command debugging
> Add more information to events to track down issue

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testPerfmonDataSource.py
Fixes ZPS-1015
* missed this add_event in fix for 831
> Add datasource arguments

- ZenPacks/zenoss/Microsoft/Windows/ClusterDevice.py
Fixes ZPS-577
Updated "create_device" method to use facade instead of dmd transaction
(submits as job).  Also modified to set zProperties per the cluster
settings.
> Add Cluster nodes automatically (ZPS-577)

- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
> Make sure to compare correct case

- ZenPacks/zenoss/Microsoft/Windows/migrate/RemoveWinRMServices.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/ResetClassTypes.py
Fixes ZPS-959
no need to blow things up.  let's issue a warning to rerun the install after stopping zenjobs
> No need to blow up the install

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
Fixes [ZPS-1149](https://jira.zenoss.com/browse/ZPS-1149).
> ZPS-1149: Fix tracebacks in zenpython.

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/IIS.py
> Correct IIS version in component details panel

- ZenPacks/zenoss/Microsoft/Windows/jobs.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/ResetClassTypes.py
Fixes ZPS-1178, ZPS-959
* Add logging to inform user what is going on
* Chunkify the migration for larger infrastructures
* Remove any pesky old winrmservices from componentSearch
> Chunkify resetting class types.  Remove broken winrmservices

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
Fixes ZPS-1158.
Incorrect event for MSSQL components appeared in case new database was created on target device but was not modeled in Zenoss, to fix this:
Added validation to create events only for existing components;
Added checker to prevent AttributeError for such particular case.
> Fix traceback in event for MSSQL components

- ZenPacks/zenoss/Microsoft/Windows/migrate/MigrateDBInstances.py
Just a note that I was unable to actually duplicate the issue, but I suspect it is limited to long-running platform installations that have been through many upgrades of the Windows ZP (dating back to at least 2.1.0).  In that sense this fix is speculative, but I don't believe it will cause any harm.
- Fixes ZPS-870
- Updated MigrateDBInstances to test all device classes and devices for
invalid values
- Issue may result from missed migration targets in 2.1 version (so a
long-standing but mostly dormant issue)
> Ensure zDBInstances is stored as a string (ZPS-870)

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testAuthErrEvents.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-562
update unit test
> Remove mappings from event classes, set eventclasskeys only

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testShellDataSource.py
Fixes [ZPS-1146](https://jira.zenoss.com/browse/ZPS-1146).
Correctly join some lines in output to avoid situations when test name
jumps to next line.
> ZPS-1146: Parse correct test name instead of "Unknown"

- ZenPacks/zenoss/Microsoft/Windows/basereportable.py
Fixes https://jira.zenoss.com/browse/ZPS-1239.
> ZPS-1239: Propper proper type of Windows filesystems

- README.mediawiki
- docs/Makefile
- docs/body.md
- docs/header.md
- docs/releases.md
- docs/template.html
- docs/windows.html
Fixes ZPS-851, ZPS-1008
Create markdown, html, update screenshots, add harddisk screenshot
> Initial move from mediawiki to markdown+html

- README.mediawiki
- docs/body.md
- docs/windows.html
Fixes ZPS-1008
rename 10.111.5.171 to <device>
> add harddisks to modeler plugins, note about discontinuing win2008

- ZenPacks/zenoss/Microsoft/Windows/tests/testEventLogDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testIISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testProcessDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testShellDataSource.py
Fixes https://jira.zenoss.com/browse/ZPS-1255
> ZPS-1255: Reflect fix for duplicate clear events

- ZenPacks/zenoss/Microsoft/Windows/migrate/RemoveWinRMServices.py
- Updated RemoveWinRMServices to continue if winrmservices relation is
not found
> Prevent AttributeError during migrate from terminating installation

- ZenPacks/zenoss/Microsoft/Windows/migrate/AddStateToWinService.py
> Make sure subclasses have WinService state datapoint

- ZenPacks/zenoss/Microsoft/Windows/migrate/AddStateToWinService.py
> Make sure we update device local templates also

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/HardDisks.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testHardDisks.py
Fixes ZPS-1279
Also added unit test
> Serial number could be None, which has no strip() method

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
Due to timing issues, the LongRunningCommandClient does not
seem to behave well for pulling perfmon counters in PerfmonDataSource.
Reverting back to the previous client.  Found issue while diagnosing
issue for customer.  Reverting fixed their issue.
> Revert back to original long_running_command

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
-Update ShellDataSource WinSQL Job Strategy to reflect template severity
choice instead of hard-coded value
> WinSQLJob events should use template severity (ZPS-1322)

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- docs/body.md
- docs/releases.md
> write out database name in case no counter data returned

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/IISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- docs/body.md
- docs/releases.md
- docs/windows.html
Fixes ZPS-1368
Removed unnecessary function to convert counter instances
Also fixed issue when trying to copy iissites template
> No need to convert to unicode as we support utf-8 now

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/HardDisks.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testHardDisks.py
- docs/body.md
Fixes ZPS-1424
also update unit test
> Handle invalid Size on HardDisk

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- docs/body.md
Fixes ZPS-1600
start maintenance when we start collection
> Do not start persister when module is loaded

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
- docs/body.md
> aliases should be in lowercase for analytics

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testWinMSSQL.py
- docs/body.md
Fixes ZPS-1676
Also reworked job modeling to be more in line with dbs/backups.
Updated unit tests to make sure we're creating oms correctly from
model input
> Handle traceback when modeling sql jobs

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/migrate/AddDPToIISDataSource.py
Fixes ZPS-1770
Check for RequestError.  Emit message saying we're restarting get-counter
> Handle restart of shell in LongRunningCommand

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/jobs.py
- docs/body.md
Fixes ZPS-1783
also added some updates to the readmes
> invalidate service object to free up memory

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/ClusterInterface.py
- docs/body.md
Fixes ZPS-1852
We should not match on empty ipaddresses and we should only look
for node within /Server/Microsoft
> Find cluster node correctly

- ZenPacks/zenoss/Microsoft/Windows/tests/createdevice.py
> update createdevice to create multiple devices with multiple services

- ZenPacks/zenoss/Microsoft/Windows/info.py
- ZenPacks/zenoss/Microsoft/Windows/interfaces.py
fixes [ZPS-2042](https://jira.zenoss.com/browse/ZPS-2042).
> Remove redundant property `formatted_description` from WinSerice.

- ZenPacks/zenoss/Microsoft/Windows/datasources/IISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes [ZPS-1632](https://jira.zenoss.com/browse/ZPS-1632).
> Classify certain Unknown events

- ZenPacks/zenoss/Microsoft/Windows/EventPlugins.py
- ZenPacks/zenoss/Microsoft/Windows/configure.zcml
- docs/body.md
> Update message for DNS lookup failed events

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-2110
Fix graph point so it displays correctly
> Fix graph point definitions for rrd datapoints

- ZenPacks/zenoss/Microsoft/Windows/datasources/IISSiteDataSource.py
> Use unique eventKey for Appliation pool status

- ZenPacks/zenoss/Microsoft/Windows/utils.py
Fixes ZPS-1843
Default class should not be /Unknown
> change default event class to /Status/Winrm

- README.mediawiki
- docs/body.md
Fixes ZPS-2083
Add possible symptom to docs for zWinRMEnvelopeSize property
> Update documentation for envelope size symptom

- ZenPacks/zenoss/Microsoft/Windows/modeler/WinRMPlugin.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/IIS.py
- docs/body.md
> Fix events for IIS Site components

- ZenPacks/zenoss/Microsoft/Windows/migrate/RemoveEventInst.py
Fixes https://jira.zenoss.com/browse/ZPS-2106
> ZPS-2106: Fix Warnings zenpack during upgrade

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
Fixes [ZPS-2130](https://jira.zenoss.com/browse/ZPS-2130)
> Add checks to WinCluster modeler plugin to prevent errors in case no data received

- ZenPacks/zenoss/Microsoft/Windows/EventPlugins.py
> Fix traceback during checking event classes

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
> hide attribute from details display

- ZenPacks/zenoss/Microsoft/Windows/tests/testIISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testShellDataSource.py
Fixes [ZPS-1632](https://jira.zenoss.com/browse/ZPS-1632).
> Add unittest for `onError` method

- ZenPacks/zenoss/Microsoft/Windows/event_classes.yaml
> Add missing EventClass for thresholds of Interface components

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Software.py
- docs/body.md
Fixes https://jira.zenoss.com/browse/ZPS-2139
Change will fix incorrect software manufacturers only on the new devices
Signed-off-by: Vadym Byshovets <byshovets@gmail.com>
> ZPS-2139: Fix Unknown Software Manufacturer

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Software.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testSoftware.py
- docs/body.md
Fixes https://jira.zenoss.com/browse/ZPS-1245
Some Windows systems may report duplicated software products installed.
Signed-off-by: Vadym Byshovets <byshovets@gmail.com>
> ZPS-1245: Some software shows up duplicated

- README.mediawiki
- docs/body.md
Fixes ZPS-1853
It also describes how to run a job manually
> Document the need to stop zenjobs during upgrade

- ZenPacks/zenoss/Microsoft/Windows/event_classes.yaml
Fixes [ZPS-2100](https://jira.zenoss.com/browse/ZPS-2100).
> Fix warings during zenpack uninstallation.

- README.mediawiki
- docs/body.md
Update for https://jira.zenoss.com/browse/ZPS-2139 and
https://jira.zenoss.com/browse/ZPS-1245.
> Document workaround for several Software issues.

- ZenPacks/zenoss/Microsoft/Windows/Device.py
- ZenPacks/zenoss/Microsoft/Windows/device_classes.yaml
- ZenPacks/zenoss/Microsoft/Windows/migrate/AddMSExchangeTemplates.py
Fixes [ZPS-2187](https://jira.zenoss.com/browse/ZPS-2187).
> Fix bound device templates display on the left side pane

- README.mediawiki
- ZenPacks/zenoss/Microsoft/Windows/__init__.py
- docs/body.md
> Remove duplicate datasources when Exchange ZenPack is removed

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
Fixes [ZPS-2229](https://jira.zenoss.com/browse/ZPS-2229).
> Set defined eventClass for SQL Instance instead of hard-coded '/Status'

- README.mediawiki
- docs/body.md
Fixes ZPS-2340
sql server 2005 past end of life from microsoft.  removing our support
> Remove sql server 2005 support

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- docs/body.md
Fixes ZPS-2433
We also need to update the ipaddress in the conn_info when we're sending powershell
script to host to pull db counters
> Change ip address when changing hostname for sql db datasources

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
Fixes ZPS-2437
We should include unpartitioned disks also, not just those with partitions and volumes
> model unpartitioned cluster disks

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- docs/body.md
> Change default event severity to Info when no severity from Windows

- ZenPacks/zenoss/Microsoft/Windows/modeler/WinRMPlugin.py
- docs/body.md
> Use single eventKey so same error is not duplicated

- ZenPacks/zenoss/Microsoft/Windows/tests/testEventLogDataSource.py
> Update unit test to account for invalid/missing windows event type

- README.mediawiki
- docs/body.md
Also remove invalid lines from mediawiki
> Fix Impact version typo for 2.8.1, 2.8.2

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- docs/body.md
Fixes ZPS-2613
Also define owner_node_ip by default.
> Make sure context has attribute

- docs/body.md
> fix parser code so it looks right

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Software.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testSoftware.py
- docs/body.md
Fixes ZPS-2745
Update unit test also
> Strip whitespace so that we correctly checkValidId

- ZenPacks/zenoss/Microsoft/Windows/__init__.py
- docs/body.md
Fixes [ZPS-2755](https://jira.zenoss.com/browse/ZPS-2755).
> Remove 'Exchange - RPC Latency' graph if Exchange ZP is installed

- ZenPacks/zenoss/Microsoft/Windows/__init__.py
- docs/body.md
Fixes ZPS-2197
There is no need for this any more.  i think there may have been an issue with the testers system as the counters are valid
> No need to remove datapoints/graphs

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- docs/body.md
Fixes ZPS-2925
Use the client collector timeout to determine how long to wait for the WinMSSSQL plugin to run.
> Fix modeling sql server

- ZenPacks/zenoss/Microsoft/Windows/datasources/IISSiteDataSource.py
Fixes ZPS-2728
If user does not install IIS Management Scripts and Tools, we can account for the missing wmi class.  Also add message so that they will be informed to install the required scripts/tools on their device.
> Account for IIS scripts/tools not installed on iis7+

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
> One more place to remove hardcoded event class

- ZenPacks/zenoss/Microsoft/Windows/tests/testShellDataSource.py
> Fix unit test

- ZenPacks/zenoss/Microsoft/Windows/modeler/WinRMPlugin.py
Fixes ZPS-3097
Need to create client per command due to session management architecture
> create client per command

- docs/body.md
> Add note warning of multiple severity events for services

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
- docs/body.md
> No need to show 'None' as the Service Pack

- ZenPacks/zenoss/Microsoft/Windows/actions.py
- ZenPacks/zenoss/Microsoft/Windows/txwinrm_utils.py
Fixes ZPS-3136
use getattr to pull in default z property
> HyperV device may not have all z properties

- ZenPacks/zenoss/Microsoft/Windows/tests/data/ClusterDataSourcePlugin_onSuccess_161027.pickle
- ZenPacks/zenoss/Microsoft/Windows/tests/data/Interfaces_process_194131.pickle
- ZenPacks/zenoss/Microsoft/Windows/tests/testClusterDataSource.py
Fixes ZPS-3129
also fixed cluster datasource test for 4.2.5
> Fix pickles for 4.2.5 unit tests

- ZenPacks/zenoss/Microsoft/Windows/datasources/ProcessDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testProcessDataSource.py
> Place collection errors into /Status

- ZenPacks/zenoss/Microsoft/Windows/device_classes.yaml
Fixes ZPS-582
Added graph to show free space.  removed threshold because of previous percentage issues with filesystems, etc.
> add cluster disk free space graph, remove threshold

- ZenPacks/zenoss/Microsoft/Windows/device_classes.yaml
> use base 1024 to show bytes

- ZenPacks/zenoss/Microsoft/Windows/HardDisk.py
- ZenPacks/zenoss/Microsoft/Windows/configure.zcml
- ZenPacks/zenoss/Microsoft/Windows/migrate/ReindexHardDiskSearchKeywords.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/HardDisks.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-2905.
* Update HardDisk.storage_disk_lun method to find storage providers with 'has-target-wwn' ids
* Add HardDisk.disk_ids to searchKeywords
* Update impact for HardDisk components
> Update links to storage providers for HardDisk components

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
> remove log message used during testing

- ZenPacks/zenoss/Microsoft/Windows/actions.py
- docs/body.md
Fixes ZPS-3422
Also update docs with note about dns lookups
> use newer SingleCommandClient for wincommand

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
> be sure there is a reason perfmon didn't start

- ZenPacks/zenoss/Microsoft/Windows/BaseDevice.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
> Fix clearing events for non-existent components

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
Made regex non-greedy, it now stops at the first match.  Before it found final stack-trace and kept everything before.
Changed 'or' logic to 'and' for testing regex group has value
> changed regex to be non-greedy (before only eliminated last stack-trace)

- ZenPacks/zenoss/Microsoft/Windows/utils.py
- docs/body.md
fixes ZPS-4198
update readme with information on auto close.
> add support for sql server 2017

- ZenPacks/zenoss/Microsoft/Windows/device_classes.yaml
A copy of https://github.com/zenoss/ZenPacks.zenoss.Microsoft.Windows/pull/1030
It should've been merged into this branch
> fix time graph

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
'status' db resources now return data
> fix for ZPS-3194

- docs/body.md
> add external jiras to changes section

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinCluster.py
Fixes ZPS-5519
get-ciminstance returns a different object than get-wmiobject.  need to use get-cimassociatedinstance instead of .GetRelated() to get the proper objects
> update powershell to get disks correctly

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
> update event key so it can be cleared

- ZenPacks/zenoss/Microsoft/Windows/migrate/AddClusterOwnerChange.py
- docs/body.md
fixes ZPS-4887
ensure clusterOwnerChange event class key is in zWindowsRemodelEventClassKeys
> add migrate script for zWindowsRemodelEventClassKeys

- ZenPacks/zenoss/Microsoft/Windows/datasources/IISSiteDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/IIS.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testIIS.py
[ZPS-5407](https://jira.zenoss.com/browse/ZPS-5407)
- get DefaultAppPool in case we can't get it from iisVirt
- fix typo in datasource error
- add this case to the u/tests
> ZPS-5407: fix getting DefaultAppPool

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
[ZPS-4866](https://jira.zenoss.com/browse/ZPS-4866)
> ZPS-4866: fix debug log

- ZenPacks/zenoss/Microsoft/Windows/device_classes.yaml
- ZenPacks/zenoss/Microsoft/Windows/migrate/AddClusterOwnerChange.py
Fixes ZPS-4887
clusterOwnerChange only applies to clusters.  make sure the property is set on any z prop under /Server/Microsoft/Cluster including the device class
> be sure /Server/Microsoft/Cluster gets zprop assigned

- ZenPacks/zenoss/Microsoft/Windows/migrate/AddClusterOwnerChange.py
fixes ZPS-4887
can't add string to lists.  need to add lists to lists
> update get_objects to avoid add error

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
[ZPS-5553](https://jira.zenoss.com/browse/ZPS-5553?filter=-1)
> ZPS-5553: rewrite status label to be more explicit

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
[ZPS-5158](https://jira.zenoss.com/browse/ZPS-5158)
show /Status/MSSQL eventClass for events connected to MSSQL
> ZPS-5158: fix MSSQL events

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
[ZPS-5169](https://jira.zenoss.com/browse/ZPS-5169?filter=-1)
> feature/ZPS-5169: fix cycletime for mssql jobs

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testEventLogDataSource.py
- docs/body.md
[ZPS-5585](https://jira.zenoss.com/browse/ZPS-5585?filter=-1)
> ZPS-5585: fix severity and eventClass in eventlog

- ZenPacks/zenoss/Microsoft/Windows/tests/testShellDataSource.py
[ZPS-5169](https://jira.zenoss.com/browse/ZPS-5169)
> Feature/zps 5169 Twisted u/tests for collect func

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- docs/body.md
> need to send clear event for sql job collection

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
[ZPS-5585](https://jira.zenoss.com/browse/ZPS-5585)
> ZPS-5585: fix event class key

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/OperatingSystem.py
[ZPS-5622](https://jira.zenoss.com/browse/ZPS-5622)
> ZPS-5622: handle all exceptions for sysEnclosure

- ZenPacks/zenoss/Microsoft/Windows/tests/test_utils.py
- ZenPacks/zenoss/Microsoft/Windows/tests/utils.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- docs/body.md
Fixes ZPS-5676
also write unit tests to cover this situation
> check to be sure CommandLine exists, and not None

- docs/body.md
> update docs to explain why we show N/A for cluster disk space

- docs/body.md
fixes ZPS-5821
be sure users know it is their responsibility to maintain lpu
> update doc with LPU disclaimer

- docs/body.md
> update docs to be more descriptive of where to run tcpdump

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
> ensure 'unexpected response' is caught

- ZenPacks/zenoss/Microsoft/Windows/__init__.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/txwinrm_utils.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Implements ZPS-7366.
* Model SQL Instances with Always On resources on them.
* Add Always On capabilities to WinMSSQL modeller plugin.
* Add zSQLAlwaysOnEnabled property for enabling/disabling Always On functionality.
> Model SQL Instances with Always On resources

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
> Update config key to monitor all SQL Instances

- ZenPacks/zenoss/Microsoft/Windows/WinSQLInstanceHostedObject.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/device_classes.yaml
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Implements ZPS-7437.
Add incremental modeling and events for Availability Replica component.
What were added is described in [Jira comment](https://jira.zenoss.com/browse/ZPS-7437?focusedCommentId=183749&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-183749)
> Add incremental modeling and events for Replica

- ZenPacks/zenoss/Microsoft/Windows/__init__.py
- ZenPacks/zenoss/Microsoft/Windows/txwinrm_utils.py
We need better timeout control in txwinrm library.
Fixes ZPS-7329
> Add better timeouts control

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
Fixes ZPS-7457
We need to update conn_info every collection cycle
to support CyberArk
> Update conn_info every collection cycle

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Implements ZPS-7454.
Add Availability Group Listener component.
Add modeling capabilities for Availability group component.
Add WinSQLAvailabilityGroup(winsqlavailabilitylisteners) 1:MC (winsqlavailabilitygroup)WinSQLAvailabilityListener relation.
> Add Availability Group Listener component

- ZenPacks/zenoss/Microsoft/Windows/WinSQLAvailabilityReplica.py
- ZenPacks/zenoss/Microsoft/Windows/__init__.py
- ZenPacks/zenoss/Microsoft/Windows/device_classes.yaml
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
> Add monitoring capabilities for Replica component

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/device_classes.yaml
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
> Incremental modeling and events for Listener component

- ZenPacks/zenoss/Microsoft/Windows/migrate/UpdateAlwaysOnRelations.py
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Implements ZPS-7470.
* Add modeling capabilities for Availability databases.
* Add WinSQLAvailabilityReplica(databases) 1:M (winsqlavailabilityreplica)WinSQLDatabase relation.
* PowerShell script length optimization.
> Modeling of Availability databases

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/device_classes.yaml
- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
Fixes ZPS-7465.
* Collect info about replicas and group from all Windows nodes on which Availability Group is placed.
* Remove modeling of some Always On properties which then obtain during monitoring.
* Some small fixes and refactoring.
> Collect inf about replicas & group from all nodes

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
> Add checks for cluster_node_server parameter

- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
Fixes ZPS-7433
For some reason Win Server 2016 Datacenter has issues with assignment
by addition operator in some commands (potentially a bug on the Win
side)
> Fix issue with Cluster datasource

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Fixes ZPS-7469.
Collect IDs and relations for Replica and SQL Instance without direct access to SQL Instances.
> Collect additional data for some AO components

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Fixes ZPS-7451.
Set IP address and SQL Instance version before collection on particular SQL Instance.
In case the SQL Instance is inaccessible there will be data about SQL Instance IP address and version.
> Set IP addr and SQL ver before instance collection

- ZenPacks/zenoss/Microsoft/Windows/utils.py
> Add SQL assembly ver 15 to support SQLServer 2019

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Fixes ZPS-7513.
Provide separate additional data to each per-SQL instance collection to avoid incorrect data values
which may come from another Windows nodes.
> Separate additional data to per-instance collection

- docs/body.md
> Doc update

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
Fixes ZPS-7520.
Always On collection only on non clustered Instances as Availability replicas can be placed on
standalone SQL Instances.
> AO collection only on non clustered Instances

- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/device_classes.yaml
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
> Add 'status' datapoint to Windows Services

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/WinMSSQL.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Implements ZPS-7484.
* Add Port and Network mode properties to Listener component.
* Cluster Availability Group list PowerShell script length shrink.
> Add Port and Network mode to Listener component

- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
> Remove os link from SQL AG component

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
> Fix wrong PerfmonDataSourcePlugin property name

- docs/body.md
> Methion CPU Utilization ticket in, small doc fixes

- ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Processes.py
removing old RM 4.x code
Updating for ZPA compatibility
Addresses: ZING-13517, ZING-14706
Note, there are no functional changes.
> Updating for ZPA compatibility

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/txwinrm_utils.py
No change in functionality.  I just noticed some edge-cases that needed to be addressed when working in ZenPackAdapter
> updates to Windows ZP

- docs/body.md
> Document changes made in scope of epic

- docs/body.md
> Documents the need of increasing MaxShellsPerUser

- docs/body.md
> Documentation update in scope of release

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
Fixes ZPS-7928.
Handle CannotCreateTypeConstrainedLanguage monitoring device exception
> Fix ConstrainedLanguage exception handling

- docs/body.md
> Documentation update

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
> Fix MSSQL Always On unnecessary datamaps applying

- ZenPacks/zenoss/Microsoft/Windows/datasources/PerfmonDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testPerfmonDataSource.py
Fixes ZPS-8015.
Added WinRM port check before LongRunning command execution. 
This prevents PerfMon datasource from hanging when one of the hosts 
with Kerberos authentication stops receiving WinRM connections. 
Added correct default values to counters dict to prevent possible attribute errors. 
Added appropriate unit test.
> Fix failed perfmon collection for Windows hosts

- ZenPacks/zenoss/Microsoft/Windows/datasources/ServiceDataSource.py
Fixes ZPS-8544.
Changed zFailSeverity attribute retrieving method to get
> Fix honoring Windows service zFailSeverity

- ZenPacks/zenoss/Microsoft/Windows/datasources/ShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/ms_sql_always_on_test_data.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testShellDataSource.py
Fixes ZPS-5264.
Replace MSSQL JobName by JobID in parse_results
Add Unit tests for MSSQLJobSQLStrategy
> Fix MSSQL Job Strategy parse_results method

- ZenPacks/zenoss/Microsoft/Windows/actions.py
- ZenPacks/zenoss/Microsoft/Windows/datasources/ClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testClusterDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/test_ScheduleRemodel.py
Fixes ZPS-7883
Changed pattern to match remodeling and prevent multiple status event creation.
> Fix pattern match on Windows Cluster Remodel

- ZenPacks/zenoss/Microsoft/Windows/migrate/UpdatezWinServicesGroupedByClass.py
- ZenPacks/zenoss/Microsoft/Windows/zenpack.yaml
Fixes ZPS-8441.
Update zWinServicesGroupedByClass with a requested list of services.
> Add default services to zWinServicesGroupedByClass

- ZenPacks/zenoss/Microsoft/Windows/tests/testShellDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
Implements ZPS-8540.
Added method that extracts all statuses from a status numeric value. 
Added unit tests.
> Add complex DB statuses processing in Shell ds

- ZenPacks/zenoss/Microsoft/Windows/datasources/EventLogDataSource.py
- ZenPacks/zenoss/Microsoft/Windows/tests/testEventLogDataSource.py
Fixes ZPS-8634.
Added regex for XML header excluding.
Cleared whitespaces for XML values.
Added unit test.
> Fix 'Event Query' field parsing

- ZenPacks/zenoss/Microsoft/Windows/tests/test_utils.py
- ZenPacks/zenoss/Microsoft/Windows/utils.py
Fixes ZPS-7967.
Fixed "'NoneType' object has no attribute 'lower'" errors during MSSQL components modelling.
> Fix attribute error during MSSQL plugin modeling

- ZenPacks/zenoss/Microsoft/Windows/utils.py
> Add MSSQL Server Assembly for MSSQL Server 2022

- docs/body.md
> Add a note about Analytics usage

- docs/body.md
> Add the LPU script usage specifics to the docs

- ZenPacks/zenoss/Microsoft/Windows/configure.zcml
- ZenPacks/zenoss/Microsoft/Windows/jobs.zcml
> Register Windows ZP jobs via jobs.zcml file

- docs/body.md
> Document Cluster parent discovery by node

- ZenPacks/zenoss/Microsoft/Windows/tests/testIISSiteDataSource.py
> Add the zProperty to the mock config in tests

- docs/body.md
- docs/releases.md
> Add the docs in the scope of 3.1.1 release

- ZenPacks/zenoss/Microsoft/Windows/migrate/RemoveSoftwareModelerPluginFromDefaults.py
> Remove Non-ASCII characters
